In [1]:
import numpy as np

In [4]:
#w1->P3
# CH3OH = trans-HCOH + H2


cheby_W1_P3_fit= np.array([-37.203049342069086+np.log10(6.0221409e+23), 0.3808325712164322, 0.008129480001032086, -0.017292854090452003, -0.0035617441423116958, 42.91396982476409, 0.6608979691084977, 0.024231199578799045, -0.02857040755214868, -0.00966780688736435, -0.35106902403316376, 0.42628698908939366, 0.06050397830744447, -0.020592142878387953, -0.004101091158683623, -0.42849325712592545, 0.2181144179223118, 0.05032947915200481, -0.0004759004020167268, -0.005530480565491616, -0.2518572228569589, 0.08305164897012673, 0.0375706061438672, 0.007572553838845586, 0.0002307525070479599, -0.1546924650617012, 0.024330366212605092, 0.01080112177722059, 0.009218210875725275, 0.0006028955007332526, -0.08489906099832956, 0.0011731629872003269, 0.0007935214224215059, 0.003210580180415956, 0.001567949721067663, -0.04712621405610573, -0.0030724041102543004, -0.004869779975743782, -0.00011165334288446883, -0.0001515289134395026, -0.02636490842903516, -0.0008697376982778598, -0.00708407405400191, -1.984747277828172e-06, -0.0018933588118081879, -0.01219464737495457, -0.0009188200211209044, -0.0011890356148800407, -0.0006002372940888175, -0.0003847877196583305, -0.008183809586845836, 0.002815886937612813, -0.006108230718650187, 0.0020895009428759455, -0.0021944848712855958, -0.001890945833470714, -0.00032068300252078956, 0.001330313380157655, -3.8707752758489894e-05, 0.0005148409281544586, -0.003980203082798006, 0.0032197475064514106, -0.0069629473044483525, 0.0025170424734657663, -0.0023783349447130675, -4.040802579741154e-05, -0.0004388897469462731, 0.0007110836605974669, -0.0001618698226486569, 0.0003153636170583063, -0.0026790067140116114, 0.0026602493276379766, -0.0060476109424527635, 0.001966187882458073, -0.0021077094902386406])

cheby_W1_P3_fit = cheby_W1_P3_fit.reshape((15,5))


#pd.DataFrame(cheby_P3_P4_fit)
cheby_W1_P3_fit

array([[-1.34232984e+01,  3.80832571e-01,  8.12948000e-03,
        -1.72928541e-02, -3.56174414e-03],
       [ 4.29139698e+01,  6.60897969e-01,  2.42311996e-02,
        -2.85704076e-02, -9.66780689e-03],
       [-3.51069024e-01,  4.26286989e-01,  6.05039783e-02,
        -2.05921429e-02, -4.10109116e-03],
       [-4.28493257e-01,  2.18114418e-01,  5.03294792e-02,
        -4.75900402e-04, -5.53048057e-03],
       [-2.51857223e-01,  8.30516490e-02,  3.75706061e-02,
         7.57255384e-03,  2.30752507e-04],
       [-1.54692465e-01,  2.43303662e-02,  1.08011218e-02,
         9.21821088e-03,  6.02895501e-04],
       [-8.48990610e-02,  1.17316299e-03,  7.93521422e-04,
         3.21058018e-03,  1.56794972e-03],
       [-4.71262141e-02, -3.07240411e-03, -4.86977998e-03,
        -1.11653343e-04, -1.51528913e-04],
       [-2.63649084e-02, -8.69737698e-04, -7.08407405e-03,
        -1.98474728e-06, -1.89335881e-03],
       [-1.21946474e-02, -9.18820021e-04, -1.18903561e-03,
        -6.00237294e-04

In [5]:
#W1->P2
#CH3OH =cis-HCOH + H2
cheby_W1_P2_fit = np.array([-39.14188584318778+np.log10(6.0221409e+23), 0.5916176565640932, -0.032218569238334105, -0.019059013500243083, -6.128476046640685e-05, 44.2598356983202, 0.914238987840637, 0.011286512153170808, -0.0463010753521198, -4.27931300279738e-05, -0.5030490936645498, 0.4869304458468675, 0.07924758839246351, -0.0280958059837908, -0.003402294994456767, -0.43982329800907927, 0.21072981239229271, 0.05562844279046608, 0.008186058803343776, -0.0075958677609267895, -0.2574347771442369, 0.07226964160543226, 0.03298693632097516, 0.015176281354028376, 0.0018544772288713318, -0.15209916073511365, 0.018083729563571183, 0.005939851014170383, 0.009145641852472242, 0.002545298910602914, -0.0848989518910288, -0.0007109966876928109, -0.003468647049297502, 0.001000865514621023, 0.0009958987453182466, -0.047220955779279095, -0.002136667413873373, -0.0070346698089274184, -0.000654084619666765, -0.0014357068049246635, -0.025574877243801364, 0.0006227316144911815, -0.006801161145551848, 0.0006809195443016128, -0.002210378460199225, -0.011531272999924846, 0.00014411401395497334, -0.00044962957886607313, 9.898475261442552e-05, -8.768144791337917e-05, -0.007405934228751132, 0.0023470467319555433, -0.0052341877760063715, 0.0021238668556718236, -0.0018334405665223485, -0.0020212297059444273, -0.0005165724720446671, 0.001062948123462526, -0.000104034170403694, 0.000498352681827352, -0.003581733438186241, 0.00232554580044988, -0.006637825129827579, 0.002238221908198102, -0.0023573536165164555, -0.0001949915786330081, -0.00043112843987796676, 0.0004601737492329061, -0.0001760392549958814, 0.00022934556373011006, -0.0022509970888708875, 0.0021212359124414062, -0.005580823467755458, 0.00182459190512433, -0.0020272411756394604])

cheby_W1_P2_fit = cheby_W1_P2_fit.reshape((15,5))

cheby_W1_P2_fit


array([[-1.53621349e+01,  5.91617657e-01, -3.22185692e-02,
        -1.90590135e-02, -6.12847605e-05],
       [ 4.42598357e+01,  9.14238988e-01,  1.12865122e-02,
        -4.63010754e-02, -4.27931300e-05],
       [-5.03049094e-01,  4.86930446e-01,  7.92475884e-02,
        -2.80958060e-02, -3.40229499e-03],
       [-4.39823298e-01,  2.10729812e-01,  5.56284428e-02,
         8.18605880e-03, -7.59586776e-03],
       [-2.57434777e-01,  7.22696416e-02,  3.29869363e-02,
         1.51762814e-02,  1.85447723e-03],
       [-1.52099161e-01,  1.80837296e-02,  5.93985101e-03,
         9.14564185e-03,  2.54529891e-03],
       [-8.48989519e-02, -7.10996688e-04, -3.46864705e-03,
         1.00086551e-03,  9.95898745e-04],
       [-4.72209558e-02, -2.13666741e-03, -7.03466981e-03,
        -6.54084620e-04, -1.43570680e-03],
       [-2.55748772e-02,  6.22731614e-04, -6.80116115e-03,
         6.80919544e-04, -2.21037846e-03],
       [-1.15312730e-02,  1.44114014e-04, -4.49629579e-04,
         9.89847526e-05

In [6]:
#W1->P1
#CH3OH =CH2 + H2O
cheby_W1_P1_fit = np.array([-38.79146404587064+np.log10(6.0221409e+23), 1.1838147960566872, -0.44822997226041394, 0.14045723738383575, -0.03333771144262876, 45.31712758086461, 0.7970321150445727, 0.022800347680773575, -0.0556639824208327, 0.029554765428812857, -0.7748954246151936, 0.29300799438641123, 0.08471036099903113, -0.025364322245108983, -0.012769593720075356, -0.4592157621936561, 0.13163126613165232, 0.06550508062233362, 0.007357633666494223, -0.004682818861564769, -0.2596657274947596, 0.05826035084288694, 0.036852269071455446, 0.01240887984091188, 0.0027218798102826014, -0.14077886142619733, 0.015398491119033686, 0.02275386906165089, 0.0023948132873612415, 0.006237918682586151, -0.07870358016110979, 0.00010838866679141468, 0.0068514728549682324, -0.000888265828859619, 0.0023916123051912486, -0.042677827790510214, -0.004164085361972592, 0.0019199971185566156, -0.0021244553404225486, 0.0008931501377849038, -0.021530748005005318, -0.004218598334730095, 0.002387253806395817, -0.0023881709604989393, 0.0011845070244218547, -0.012470333899768926, -0.0010022499973418725, -0.0017237743453661913, 0.00014326413208690103, -0.0006668716230615601, -0.0032717087330063066, -0.002780312007967165, 0.004462391177806335, -0.0022207422962261733, 0.00211099692176564, -0.003778886629708156, 0.0006910002142468674, -0.002111459705445018, 0.0008882679235620305, -0.0007883901145423478, 0.0021763162671391, -0.0030004485220438484, 0.006144676776276281, -0.00280775700054859, 0.002835451100981601, -0.0006469687550936243, -4.159686561752696e-05, -0.0008354098694809409, 0.0003672246950780708, -0.00038576781181154374, 0.0031494243284012624, -0.002947135780763239, 0.005840103957084786, -0.0026349758095663006, 0.002558136298250524])

cheby_W1_P1_fit = cheby_W1_P1_fit.reshape((15,5))

cheby_W1_P1_fit


array([[-1.50117131e+01,  1.18381480e+00, -4.48229972e-01,
         1.40457237e-01, -3.33377114e-02],
       [ 4.53171276e+01,  7.97032115e-01,  2.28003477e-02,
        -5.56639824e-02,  2.95547654e-02],
       [-7.74895425e-01,  2.93007994e-01,  8.47103610e-02,
        -2.53643222e-02, -1.27695937e-02],
       [-4.59215762e-01,  1.31631266e-01,  6.55050806e-02,
         7.35763367e-03, -4.68281886e-03],
       [-2.59665727e-01,  5.82603508e-02,  3.68522691e-02,
         1.24088798e-02,  2.72187981e-03],
       [-1.40778861e-01,  1.53984911e-02,  2.27538691e-02,
         2.39481329e-03,  6.23791868e-03],
       [-7.87035802e-02,  1.08388667e-04,  6.85147285e-03,
        -8.88265829e-04,  2.39161231e-03],
       [-4.26778278e-02, -4.16408536e-03,  1.91999712e-03,
        -2.12445534e-03,  8.93150138e-04],
       [-2.15307480e-02, -4.21859833e-03,  2.38725381e-03,
        -2.38817096e-03,  1.18450702e-03],
       [-1.24703339e-02, -1.00225000e-03, -1.72377435e-03,
         1.43264132e-04

In [7]:
#W1->P6
#CH3OH =H + CH3O
cheby_W1_P6_fit = np.array([-51.985291023267465+np.log10(6.0221409e+23), 5.822695115162896, -1.1253116832551484, -0.9948289747647463, -0.13312604357749436, 53.82051160349613, -1.5155870731484704, 1.041460624153872, 0.7350140410627706, -0.1681867063291982, -0.2814760946797463, 0.04450763571517502, 0.30981615449109146, 0.20314666255855585, 0.1833244354911452, -0.39150175520116903, 0.0514177865892993, -0.05372081335889334, 0.05237090234646047, 0.020597252785206355, -0.20837184327182712, -0.055729869109485186, -0.0018477849186488982, -0.010964175700313383, 0.0045364267565695116, -0.10069923912875067, -0.05152568614448949, 0.020287242661700677, -0.015472638322016063, 0.007157871591173093, -0.06758759008534021, -0.007474837665555789, -0.006399021907555813, -0.0008868806770419013, -0.0004913440300651217, -0.044853605593122126, 0.00800941511459495, -0.017563284963308057, 0.00499297080460348, -0.004461040989113929, -0.022288562604245055, 0.0031416421427705177, -0.007335845324521806, 0.0018719072939830106, -0.0014482212566888641, -0.0028864868933835552, -0.012312976611132398, 0.008433573033448383, -0.004008516115176108, 0.0018511673963075292, -0.0063113769188389846, 0.0025146597078615496, -0.003889558815734162, 0.0013634154382958646, -0.0005296360769531105, 0.0013913817627431158, -0.007488801580562532, 0.003014683646916261, -0.001469557791301368, -8.31442893063361e-05, -0.00666333675750419, 0.009435525518145513, -0.009674383358130978, 0.0037528550279803674, -0.0018640794722584175, 0.0037763630996607844, -0.0070459159340554856, 0.004858482645352158, -0.002070679934936842, 0.000786984473541974, -0.0007510410694524516, 0.00135643683688208, -0.0032469148738711873, 0.0011187665560223325, -0.0008835305413361638])

cheby_W1_P6_fit = cheby_W1_P6_fit.reshape((15,5))

cheby_W1_P6_fit

array([[-2.82055401e+01,  5.82269512e+00, -1.12531168e+00,
        -9.94828975e-01, -1.33126044e-01],
       [ 5.38205116e+01, -1.51558707e+00,  1.04146062e+00,
         7.35014041e-01, -1.68186706e-01],
       [-2.81476095e-01,  4.45076357e-02,  3.09816154e-01,
         2.03146663e-01,  1.83324435e-01],
       [-3.91501755e-01,  5.14177866e-02, -5.37208134e-02,
         5.23709023e-02,  2.05972528e-02],
       [-2.08371843e-01, -5.57298691e-02, -1.84778492e-03,
        -1.09641757e-02,  4.53642676e-03],
       [-1.00699239e-01, -5.15256861e-02,  2.02872427e-02,
        -1.54726383e-02,  7.15787159e-03],
       [-6.75875901e-02, -7.47483767e-03, -6.39902191e-03,
        -8.86880677e-04, -4.91344030e-04],
       [-4.48536056e-02,  8.00941511e-03, -1.75632850e-02,
         4.99297080e-03, -4.46104099e-03],
       [-2.22885626e-02,  3.14164214e-03, -7.33584532e-03,
         1.87190729e-03, -1.44822126e-03],
       [-2.88648689e-03, -1.23129766e-02,  8.43357303e-03,
        -4.00851612e-03

In [8]:
#W1->P5
#CH3OH = H + CH2OH
cheby_W1_P5_fit = np.array([-42.618745146088145+np.log10(6.0221409e+23), 3.0875912108405092, -0.6970215078538207, 0.08324892690052632, 0.18474527066154778, 47.78140013826864, 0.12130323720914582, 0.5234080737397628, -0.3362783944918828, -0.09630455377750913, -0.6260011994347714, 0.24879201041987686, 0.05139151277157522, 0.06801240027457034, -0.10184885832102264, -0.3989052233694572, 0.0957202138222808, 0.04666314451043441, 0.06093692917447058, -0.01035197723284871, -0.23874997585859603, 0.011771166969922753, 0.02213910947802189, 0.018514805428009318, 0.006812337392851475, -0.13837708207038868, -0.009183820205696414, -0.0031277005627656784, 0.0043620392029852795, 9.539705796146603e-05, -0.07579447551028862, -0.006712835909514991, -0.004118090548257847, 0.000816470777993128, -0.0005346385072368953, -0.03982093747790483, -0.0024039253262714, -0.001903347115742804, 0.0007540148401815466, -9.362733605300377e-06, -0.02063695184055314, -0.0007626368829005137, -0.0019794512867301606, 0.0012418947352261789, -0.0003193998651251917, -0.009278184382601307, -0.0017071484887540983, 0.0006356065719241855, 0.0002663799207316686, 0.00037107589545759545, -0.005699720782675444, -0.00041959780728036133, -0.003904635380221677, 0.0017131383006326328, -0.001384126859426793, -0.001442262165852748, -0.0014505230168752048, 0.001114127796692177, -0.00036015802282352016, 0.0004779634411142819, -0.0025060279698592147, 0.0014291460559279004, -0.004492121712948993, 0.001610066674561067, -0.0013595323325308328, -0.00023823282633905762, 0.00014154402071457628, 0.0009528383538037755, -0.0004105110934515266, 0.00062143922041491, -0.000697442425737993, 0.0003359984546224548, -0.004451755999700602, 0.0016982152706272458, -0.0018525700351963437])

cheby_W1_P5_fit = cheby_W1_P5_fit.reshape((15,5))

cheby_W1_P5_fit


array([[-1.88389942e+01,  3.08759121e+00, -6.97021508e-01,
         8.32489269e-02,  1.84745271e-01],
       [ 4.77814001e+01,  1.21303237e-01,  5.23408074e-01,
        -3.36278394e-01, -9.63045538e-02],
       [-6.26001199e-01,  2.48792010e-01,  5.13915128e-02,
         6.80124003e-02, -1.01848858e-01],
       [-3.98905223e-01,  9.57202138e-02,  4.66631445e-02,
         6.09369292e-02, -1.03519772e-02],
       [-2.38749976e-01,  1.17711670e-02,  2.21391095e-02,
         1.85148054e-02,  6.81233739e-03],
       [-1.38377082e-01, -9.18382021e-03, -3.12770056e-03,
         4.36203920e-03,  9.53970580e-05],
       [-7.57944755e-02, -6.71283591e-03, -4.11809055e-03,
         8.16470778e-04, -5.34638507e-04],
       [-3.98209375e-02, -2.40392533e-03, -1.90334712e-03,
         7.54014840e-04, -9.36273361e-06],
       [-2.06369518e-02, -7.62636883e-04, -1.97945129e-03,
         1.24189474e-03, -3.19399865e-04],
       [-9.27818438e-03, -1.70714849e-03,  6.35606572e-04,
         2.66379921e-04

In [9]:
#W1->P4
#CH3OH = H2CO + H2

cheby_W1_P4_fit = np.array([-30.424051789048416+np.log10(6.0221409e+23), 0.4297744626579174, 0.019884641672214265, -0.025457576538551407, -0.002325192642512519, 30.180421291421343, 0.7612435789942475, 0.035777432425605105, -0.03839577629497981, -0.008297470001359386, 4.763888715422649, 0.5096560833645158, 0.058557429972912134, -0.02222539632331877, -0.003078479101169762, -0.5087445329642035, 0.25073005512853097, 0.05070201903096905, 0.0011453247272603662, -0.003973249431727499, -0.8797213596084674, 0.0735004499447598, 0.04207074598159366, 0.00872967250269907, 0.001500211065433632, -0.1953754561397596, 0.0069785961175732325, 0.012327781636808144, 0.010247061282705916, 0.0009678756235969588, 0.0650265067341087, -0.002044492863136904, -0.002515412807121642, 0.0034009229568305044, 0.001595315790525742, -0.006426535066612171, 0.002426934002679876, -0.008207212864502544, -0.0008062726762978999, -0.00017748639650339015, -0.06948166538201594, 0.0018557248629198012, -0.007344944427659761, -0.0006477589270959747, -0.002072322752110445, -0.04180118942864164, -0.0021926251560468422, 0.00012421398180517684, -0.000632016429224655, -0.0005744208276117213, 0.012055633861077997, 0.001271807807413948, -0.005324337812710134, 0.0027709390185769803, -0.0021856233000363545, 0.006671317102428853, 0.0007525765665326867, 0.0009589850855256099, 7.7846356124317e-05, 0.0007510182013556743, -0.000727321804795622, 0.0037571138951698474, -0.007195777713123075, 0.002456679937472124, -0.0022615340073643964, -0.014615607912511486, -0.0006684704523675193, 0.0007732757080596286, -0.0005890181578711087, 0.0002656426294453951, 0.0019178588428795385, 0.0015305116535235148, -0.005737708226470906, 0.0020420584701682162, -0.0022317185533378137])

cheby_W1_P4_fit = cheby_W1_P4_fit.reshape((15,5))

cheby_W1_P4_fit

array([[-6.64430088e+00,  4.29774463e-01,  1.98846417e-02,
        -2.54575765e-02, -2.32519264e-03],
       [ 3.01804213e+01,  7.61243579e-01,  3.57774324e-02,
        -3.83957763e-02, -8.29747000e-03],
       [ 4.76388872e+00,  5.09656083e-01,  5.85574300e-02,
        -2.22253963e-02, -3.07847910e-03],
       [-5.08744533e-01,  2.50730055e-01,  5.07020190e-02,
         1.14532473e-03, -3.97324943e-03],
       [-8.79721360e-01,  7.35004499e-02,  4.20707460e-02,
         8.72967250e-03,  1.50021107e-03],
       [-1.95375456e-01,  6.97859612e-03,  1.23277816e-02,
         1.02470613e-02,  9.67875624e-04],
       [ 6.50265067e-02, -2.04449286e-03, -2.51541281e-03,
         3.40092296e-03,  1.59531579e-03],
       [-6.42653507e-03,  2.42693400e-03, -8.20721286e-03,
        -8.06272676e-04, -1.77486397e-04],
       [-6.94816654e-02,  1.85572486e-03, -7.34494443e-03,
        -6.47758927e-04, -2.07232275e-03],
       [-4.18011894e-02, -2.19262516e-03,  1.24213982e-04,
        -6.32016429e-04

In [10]:
#P5->P6
#H + CH2OH = H + CH3O
cheby_P5_P6_fit = np.array([-16.56168413322883+np.log10(6.0221409e+23), 4.707345624410664e-14, -9.092726571680032e-14, 3.9745984281580604e-14, -3.4861002973229915e-14, 4.941624531522325, -5.3734794391857577e-14, 8.105321969154033e-14, -2.653433028854124e-14, 1.0658141036401503e-14, 0.16667388944398148, 7.122080702970379e-14, -1.008915173628111e-13, 3.347322419244847e-14, -3.0309088572266774e-14, 0.08920618031098926, -6.084022174945858e-14, 7.416289804496046e-14, -2.708944180085382e-14, 1.6986412276764895e-14, 0.03802055376557534, 7.777112287499222e-14, -6.694644838489694e-14, 3.602673714908633e-14, -2.9531932455029164e-14, 0.013119058633146441, -7.605027718682322e-14, 9.325873406851315e-14, -3.341771304121721e-14, 4.680977827575816e-14, 0.0033981393914787605, 7.189387973838279e-14, -6.850076061937216e-14, 3.0982161280945775e-14, -3.519406988061746e-14, 0.0003933838643236931, -6.987260162821807e-14, 6.838973831690964e-14, -2.634958223834971e-14, 2.7977620220553945e-14, -0.0003659430660590546, 3.668289630387456e-14, -4.433953204596719e-14, 1.40989650510015e-14, -2.1940782524154656e-14, -0.00045369125004732225, 4.573598444412852e-15, -1.1657341758564144e-14, 1.6844164951734797e-15, -8.659739592076221e-15, -0.00020204769448087245, -4.302157588509381e-14, 3.6193270602780103e-14, -1.7948099603759538e-14, 2.2537527399890678e-14, -7.399098622779682e-05, 6.70765526455952e-14, -6.822320486321587e-14, 2.7515316414206126e-14, -2.4303475898435067e-14, -4.6901699775614425e-05, -7.361711067133125e-14, 8.887335312124378e-14, -2.844642923993668e-14, 3.108624468950438e-14, -2.375786032243754e-05, 5.998587043754e-14, -6.389333506717776e-14, 2.386806030596489e-14, -2.3814283878209608e-14, 3.1664445527608553e-05, -3.3905820859270186e-14, 3.064215547965432e-14, -1.3850899593936816e-14, 7.549516567451064e-15])

cheby_P5_P6_fit = cheby_P5_P6_fit.reshape((15,5))

cheby_P5_P6_fit


array([[ 7.21806678e+00,  4.70734562e-14, -9.09272657e-14,
         3.97459843e-14, -3.48610030e-14],
       [ 4.94162453e+00, -5.37347944e-14,  8.10532197e-14,
        -2.65343303e-14,  1.06581410e-14],
       [ 1.66673889e-01,  7.12208070e-14, -1.00891517e-13,
         3.34732242e-14, -3.03090886e-14],
       [ 8.92061803e-02, -6.08402217e-14,  7.41628980e-14,
        -2.70894418e-14,  1.69864123e-14],
       [ 3.80205538e-02,  7.77711229e-14, -6.69464484e-14,
         3.60267371e-14, -2.95319325e-14],
       [ 1.31190586e-02, -7.60502772e-14,  9.32587341e-14,
        -3.34177130e-14,  4.68097783e-14],
       [ 3.39813939e-03,  7.18938797e-14, -6.85007606e-14,
         3.09821613e-14, -3.51940699e-14],
       [ 3.93383864e-04, -6.98726016e-14,  6.83897383e-14,
        -2.63495822e-14,  2.79776202e-14],
       [-3.65943066e-04,  3.66828963e-14, -4.43395320e-14,
         1.40989651e-14, -2.19407825e-14],
       [-4.53691250e-04,  4.57359844e-15, -1.16573418e-14,
         1.68441650e-15

In [12]:
#R->W1
#CH3 + OH = #CH3OH

cheby_R_W1_fit = np.array([-11.853300255679805+np.log10(6.0221409e+23), 1.637578961322106e-14, -2.2148949341271873e-14, 1.6431300764452317e-14, -9.547918011776346e-15, -2.115976287871696, -9.020562075079397e-15, 5.2496201830010136e-14, 2.4424906541753444e-15, 1.099120794378905e-14, -0.9634502584570347, 2.275957200481571e-14, -3.36952687973735e-14, -3.885780586188048e-16, -1.1268763699945339e-14, -0.45397492674424295, -2.8199664825478976e-14, 4.318767565791859e-14, -2.4980018054066022e-15, 1.1046719095020308e-14, -0.23544327547258814, 3.569367024169878e-14, -3.885780586188048e-14, 9.048317650695026e-15, -1.2434497875801753e-14, -0.12409693984068965, -3.930189507173054e-14, 4.088396288182139e-14, -1.1837753000065732e-14, 1.9234613901630837e-14, -0.06748995188435632, 5.1611492857261965e-14, -4.907185768843192e-14, 1.7531115448221612e-14, -1.865174681370263e-14, -0.03583409815152741, -4.055783486833775e-14, 4.6102011097559625e-14, -1.5660216179380626e-14, 1.6264767310758543e-14, -0.01788869458158915, 2.0365653607967715e-14, -2.4577562207639403e-14, 8.101158632811689e-15, -1.2850831510036187e-14, -0.010122999376492303, 1.48318857196017e-15, -2.55351295663786e-15, 6.314393452555578e-16, -1.8596235662471372e-15, -0.0024929027707669693, -1.728608575723989e-14, 6.661338147750939e-15, -6.95450641519102e-15, 5.717648576819556e-15, -0.0025924426705672132, 3.286954042280854e-14, -2.4591439995447217e-14, 1.3209919269563386e-14, -4.850286838831153e-15, 0.002088011231257833, -4.138486428550969e-14, 4.191091917959966e-14, -1.633242152632164e-14, 1.226796442210798e-14, -0.0005145933497293087, 3.528687758658222e-14, -3.0080105073437835e-14, 1.4090291433621616e-14, -1.1379786002407855e-14, 0.002360407545009796, -2.014534372651866e-14, 1.4863110742169283e-14, -8.222589276130066e-15, 2.4424906541753444e-15])

cheby_R_W1_fit = cheby_R_W1_fit.reshape((15,5))

cheby_R_W1_fit

array([[ 1.19264507e+01,  1.63757896e-14, -2.21489493e-14,
         1.64313008e-14, -9.54791801e-15],
       [-2.11597629e+00, -9.02056208e-15,  5.24962018e-14,
         2.44249065e-15,  1.09912079e-14],
       [-9.63450258e-01,  2.27595720e-14, -3.36952688e-14,
        -3.88578059e-16, -1.12687637e-14],
       [-4.53974927e-01, -2.81996648e-14,  4.31876757e-14,
        -2.49800181e-15,  1.10467191e-14],
       [-2.35443275e-01,  3.56936702e-14, -3.88578059e-14,
         9.04831765e-15, -1.24344979e-14],
       [-1.24096940e-01, -3.93018951e-14,  4.08839629e-14,
        -1.18377530e-14,  1.92346139e-14],
       [-6.74899519e-02,  5.16114929e-14, -4.90718577e-14,
         1.75311154e-14, -1.86517468e-14],
       [-3.58340982e-02, -4.05578349e-14,  4.61020111e-14,
        -1.56602162e-14,  1.62647673e-14],
       [-1.78886946e-02,  2.03656536e-14, -2.45775622e-14,
         8.10115863e-15, -1.28508315e-14],
       [-1.01229994e-02,  1.48318857e-15, -2.55351296e-15,
         6.31439345e-16

In [13]:
#P3->P4
#trans-HCOH + H2= H2CO + H2
cheby_P3_P4_fit = np.array([-22.21717355982654+np.log10(6.0221409e+23), -3.419486915845482e-14, -1.3211653993039363e-14, -4.6629367034256575e-15, -2.6645352591003757e-15, 7.1245661404598435, -1.3322676295501878e-15, 2.907396545737129e-14, -1.1324274851176597e-14, -1.9984014443252818e-15, 0.035165354185510145, 4.263256414560601e-14, -6.056266599330229e-14, 2.5757174171303632e-14, -2.2537527399890678e-14, 0.04236233891123886, -7.838174553853605e-14, 8.548717289613705e-14, -3.6415315207705135e-14, 2.7347915598774364e-14, 0.13703453377789332, 9.447997939560082e-14, -9.980904991380157e-14, 4.3520742565306136e-14, -5.1736392947532295e-14, 0.11884569630386504, -9.525713551283843e-14, 1.2601031329495527e-13, -3.447242491461111e-14, 5.839079220137933e-14, 0.0713196947949909, 7.678579994063739e-14, -7.477352070850429e-14, 3.1781001441633094e-14, -4.440892098500626e-14, 0.03353268614357008, -5.799093844016667e-14, 4.8183679268731794e-14, -2.26255646162965e-14, 2.4646951146678475e-14, 0.010172963944980046, 3.079264274119531e-14, -3.5110803153770576e-14, 1.2232402590850455e-14, -2.1219137558148304e-14, -0.00291371546423258, -1.5973116926359943e-14, 5.662137425588298e-15, -7.709544808109925e-15, -5.329070518200751e-15, -0.004583893914369086, -1.2586936701253215e-14, 1.3405943022348765e-14, -4.20128341838133e-15, 2.3647750424515834e-14, -0.005786768810151926, 4.1991150140363587e-14, -4.757305660518796e-14, 1.6812939929167214e-14, -2.0587698212892747e-14, -0.0013986772092122735, -5.181131131765104e-14, 6.727951529228449e-14, -1.946988577306019e-14, 2.5868196473766147e-14, -0.0017460142717443672, 4.123307598136172e-14, -3.8469227803261674e-14, 1.6242215905570845e-14, -1.915134717478395e-14, 0.0012562391086165456, -1.78836979947139e-14, 1.1601830607332886e-14, -8.639790272102488e-15, 2.220446049250313e-15])

cheby_P3_P4_fit = cheby_P3_P4_fit.reshape((15,5))

cheby_P3_P4_fit

array([[ 1.56257735e+00, -3.41948692e-14, -1.32116540e-14,
        -4.66293670e-15, -2.66453526e-15],
       [ 7.12456614e+00, -1.33226763e-15,  2.90739655e-14,
        -1.13242749e-14, -1.99840144e-15],
       [ 3.51653542e-02,  4.26325641e-14, -6.05626660e-14,
         2.57571742e-14, -2.25375274e-14],
       [ 4.23623389e-02, -7.83817455e-14,  8.54871729e-14,
        -3.64153152e-14,  2.73479156e-14],
       [ 1.37034534e-01,  9.44799794e-14, -9.98090499e-14,
         4.35207426e-14, -5.17363929e-14],
       [ 1.18845696e-01, -9.52571355e-14,  1.26010313e-13,
        -3.44724249e-14,  5.83907922e-14],
       [ 7.13196948e-02,  7.67857999e-14, -7.47735207e-14,
         3.17810014e-14, -4.44089210e-14],
       [ 3.35326861e-02, -5.79909384e-14,  4.81836793e-14,
        -2.26255646e-14,  2.46469511e-14],
       [ 1.01729639e-02,  3.07926427e-14, -3.51108032e-14,
         1.22324026e-14, -2.12191376e-14],
       [-2.91371546e-03, -1.59731169e-14,  5.66213743e-15,
        -7.70954481e-15

In [14]:
#P3->P5
#trans-HCOH + H2=H + CH2OH
cheby_P3_P5_fit = np.array([-24.15832327430874+np.log10(6.0221409e+23), 3.4638958368304884e-14, -1.1013412404281553e-13, 3.352873534367973e-14, -4.085620730620576e-14, 11.215804869720658, -7.749356711883593e-14, 2.3437501939227445e-13, -4.929390229335695e-14, 8.704148513061227e-14, 0.1562370682223574, 6.228351168147128e-14, -1.1068923555512811e-13, 2.3203661214665772e-14, -4.3298697960381105e-14, 0.107897792981265, -5.1958437552457326e-14, 1.3322676295501878e-13, -1.1102230246251565e-14, 5.652422974122828e-14, 0.06174083237637262, 9.43689570931383e-14, -1.163513729807164e-13, 3.5083047578154947e-14, -6.439293542825908e-14, 0.03325482956333087, -8.504308368628699e-14, 1.1657341758564144e-13, -2.992051051364797e-14, 6.493416915276384e-14, 0.016425113366672406, 8.545941732052142e-14, -8.22675261247241e-14, 3.5431726996826285e-14, -5.2735593669694936e-14, 0.0074185150520953425, -7.075590113814201e-14, 5.728750807065808e-14, -2.6332235003589943e-14, 3.3306690738754696e-14, 0.0030221234528067797, 3.3421182488169165e-14, -1.942890293094024e-14, 1.2150003225741557e-14, -1.4904744105592727e-14, 0.0015581129370511038, -3.8267999880048365e-15, -1.0658141036401503e-14, -2.9559688030644793e-15, -1.4099832412739488e-14, 0.0002685036376669503, -2.341182803178299e-14, 3.1308289294429414e-14, -9.353628982466944e-15, 3.375077994860476e-14, 0.00045272836525762916, 5.6349022670154625e-14, -7.438494264988549e-14, 2.235711615838909e-14, -3.326505737533125e-14, -0.00018990117252504213, -7.756642550482695e-14, 1.0191847366058937e-13, -2.8058284862186866e-14, 3.7969627442180354e-14, 7.421843560151409e-05, 6.656307449670607e-14, -7.538414337204813e-14, 2.4738891490905246e-14, -3.008704396734174e-14, 0.00025303865331054165, -4.030803468779709e-14, 3.597122599785507e-14, -1.67019176267047e-14, 8.659739592076221e-15])

cheby_P3_P5_fit = cheby_P3_P5_fit.reshape((15,5))

cheby_P3_P5_fit

array([[-3.78572362e-01,  3.46389584e-14, -1.10134124e-13,
         3.35287353e-14, -4.08562073e-14],
       [ 1.12158049e+01, -7.74935671e-14,  2.34375019e-13,
        -4.92939023e-14,  8.70414851e-14],
       [ 1.56237068e-01,  6.22835117e-14, -1.10689236e-13,
         2.32036612e-14, -4.32986980e-14],
       [ 1.07897793e-01, -5.19584376e-14,  1.33226763e-13,
        -1.11022302e-14,  5.65242297e-14],
       [ 6.17408324e-02,  9.43689571e-14, -1.16351373e-13,
         3.50830476e-14, -6.43929354e-14],
       [ 3.32548296e-02, -8.50430837e-14,  1.16573418e-13,
        -2.99205105e-14,  6.49341692e-14],
       [ 1.64251134e-02,  8.54594173e-14, -8.22675261e-14,
         3.54317270e-14, -5.27355937e-14],
       [ 7.41851505e-03, -7.07559011e-14,  5.72875081e-14,
        -2.63322350e-14,  3.33066907e-14],
       [ 3.02212345e-03,  3.34211825e-14, -1.94289029e-14,
         1.21500032e-14, -1.49047441e-14],
       [ 1.55811294e-03, -3.82679999e-15, -1.06581410e-14,
        -2.95596880e-15

In [15]:
#P3->P6
# trans-HCOH + H2 =  H + CH3O

cheby_P3_P6_fit = np.array([-30.098107981797916+np.log10(6.0221409e+23), 7.460698725481052e-14, -1.616484723854228e-13, 6.17284001691587e-14, -6.838973831690964e-14, 15.920431554268998, -5.1514348342607263e-14, 2.0046464488387983e-13, -2.19824158875781e-14, 6.394884621840902e-14, 0.16963273717257765, 5.595524044110789e-14, -1.553202011450594e-13, 2.55351295663786e-14, -5.062616992290714e-14, 0.11678483550345842, -3.1530333899354446e-14, 6.483702463810914e-14, -1.3766765505351941e-14, 1.3211653993039363e-14, 0.06513327769543142, 5.906386491005833e-14, -8.459899447643693e-14, 1.9317880628477724e-14, -4.3076653355456074e-14, 0.03374486387730169, -9.57012247226885e-14, 1.3500311979441904e-13, -4.551914400963142e-14, 7.217837438844299e-14, 0.016644670312619736, 1.3739009929736312e-13, -1.3378187446733136e-13, 5.5452170633074616e-14, -7.616129948928574e-14, 0.00808327676004117, -1.1936111821153617e-13, 1.0880185641326534e-13, -4.520689378395559e-14, 5.5844218138645374e-14, 0.0037993121363388838, 5.5854626479501235e-14, -7.155387393709134e-14, 2.1947721418058563e-14, -4.1217029789208937e-14, 0.0015933035788365801, 2.607289384393141e-15, -9.547918011776346e-15, -2.4390212072233908e-15, -1.1102230246251565e-14, 0.0009405358489970039, -6.885377684673344e-14, 5.3734794391857577e-14, -2.529660508843179e-14, 4.263256414560601e-14, 0.00041818008761708436, 1.2821688155639777e-13, -1.2934098236883074e-13, 4.8596543456014274e-14, -4.449218771185315e-14, 0.0003257127683531369, -1.4625800570655656e-13, 1.6575629757653587e-13, -5.3040905001466854e-14, 5.639932965095795e-14, 6.628523144380782e-05, 1.0630732405481069e-13, -1.0302869668521453e-13, 3.9333120094298124e-14, -3.674838211509268e-14, 0.00019017953361449846, -5.150047055479945e-14, 4.1300296516055823e-14, -2.1451590503929197e-14, 7.549516567451064e-15])

cheby_P3_P6_fit = cheby_P3_P6_fit.reshape((15,5))

cheby_P3_P6_fit

array([[-6.31835707e+00,  7.46069873e-14, -1.61648472e-13,
         6.17284002e-14, -6.83897383e-14],
       [ 1.59204316e+01, -5.15143483e-14,  2.00464645e-13,
        -2.19824159e-14,  6.39488462e-14],
       [ 1.69632737e-01,  5.59552404e-14, -1.55320201e-13,
         2.55351296e-14, -5.06261699e-14],
       [ 1.16784836e-01, -3.15303339e-14,  6.48370246e-14,
        -1.37667655e-14,  1.32116540e-14],
       [ 6.51332777e-02,  5.90638649e-14, -8.45989945e-14,
         1.93178806e-14, -4.30766534e-14],
       [ 3.37448639e-02, -9.57012247e-14,  1.35003120e-13,
        -4.55191440e-14,  7.21783744e-14],
       [ 1.66446703e-02,  1.37390099e-13, -1.33781874e-13,
         5.54521706e-14, -7.61612995e-14],
       [ 8.08327676e-03, -1.19361118e-13,  1.08801856e-13,
        -4.52068938e-14,  5.58442181e-14],
       [ 3.79931214e-03,  5.58546265e-14, -7.15538739e-14,
         2.19477214e-14, -4.12170298e-14],
       [ 1.59330358e-03,  2.60728938e-15, -9.54791801e-15,
        -2.43902121e-15

In [16]:
#P1->P2
# CH2 + H2O = cis-HCOH + H2

cheby_P1_P2_fit = np.array([-12.277629153599339+np.log10(6.0221409e+23), -1.1379786002407855e-15, -8.382183835919932e-15, 9.46465128492946e-15, -3.0531133177191805e-15, -0.7603819768879785, -5.842548667089886e-15, 2.7120666823421402e-14, -5.384581669432009e-15, 9.71445146547012e-15, -0.07950293940887589, -1.249000902703301e-16, -3.450018049022674e-14, -5.315192730392937e-15, -1.2406742300186124e-14, 0.10178134669834324, -5.828670879282072e-15, 4.773959005888173e-15, 3.3306690738754696e-15, -3.594347042223944e-15, 0.11177965043618943, 1.5432100042289676e-14, -1.1657341758564144e-15, 7.244205235679146e-15, -6.2450045135165055e-15, 0.08113023567689942, -2.8005375796169574e-14, -4.565792188770956e-15, -9.769962616701378e-15, 1.036063596027148e-15, 0.048339705528362725, 3.8049424722075287e-14, -4.238276396506535e-14, 1.512071717835184e-14, -1.890154699424329e-14, 0.024505781912055033, -3.9630842010862644e-14, 3.556877015142845e-14, -1.6034482769322622e-14, 1.2871648191747909e-14, 0.010196067546460439, 3.3002246768720767e-14, -3.69114461218345e-14, 1.3457117364890081e-14, -1.6344564590653476e-14, 0.002733057244750002, -2.7832337129440887e-14, 1.899869150889799e-14, -1.1737139038459077e-14, 3.733124920302089e-15, 7.166098226003836e-05, 1.3528457867839627e-14, -1.723968190425751e-14, 6.11229816760428e-15, -5.134781488891349e-16, -0.0009668781920254346, 9.25821919128822e-15, -8.944234242136417e-15, 2.6402491304367004e-15, -2.445960101127298e-15, -0.0004697455867655742, -2.135791543622645e-14, 3.1932789745781065e-14, -7.683957636839267e-15, 1.0519363158323358e-14, -0.0003027049815494884, 1.6965595595053173e-14, -2.0775048348298242e-14, 6.048113398993138e-15, -9.280770596475918e-15, 0.00018053828906906821, -7.367804283342494e-15, 3.073929999430902e-15, -2.690556111240028e-15, -1.6653345369377348e-16])

cheby_P1_P2_fit = cheby_P1_P2_fit.reshape((15,5))

cheby_P1_P2_fit

array([[ 1.15021218e+01, -1.13797860e-15, -8.38218384e-15,
         9.46465128e-15, -3.05311332e-15],
       [-7.60381977e-01, -5.84254867e-15,  2.71206668e-14,
        -5.38458167e-15,  9.71445147e-15],
       [-7.95029394e-02, -1.24900090e-16, -3.45001805e-14,
        -5.31519273e-15, -1.24067423e-14],
       [ 1.01781347e-01, -5.82867088e-15,  4.77395901e-15,
         3.33066907e-15, -3.59434704e-15],
       [ 1.11779650e-01,  1.54321000e-14, -1.16573418e-15,
         7.24420524e-15, -6.24500451e-15],
       [ 8.11302357e-02, -2.80053758e-14, -4.56579219e-15,
        -9.76996262e-15,  1.03606360e-15],
       [ 4.83397055e-02,  3.80494247e-14, -4.23827640e-14,
         1.51207172e-14, -1.89015470e-14],
       [ 2.45057819e-02, -3.96308420e-14,  3.55687702e-14,
        -1.60344828e-14,  1.28716482e-14],
       [ 1.01960675e-02,  3.30022468e-14, -3.69114461e-14,
         1.34571174e-14, -1.63445646e-14],
       [ 2.73305724e-03, -2.78323371e-14,  1.89986915e-14,
        -1.17371390e-14

In [17]:
#P1->P3
# CH2 + H2O =trans-HCOH + H2
cheby_P1_P3_fit = np.array([-11.503312036775432+np.log10(6.0221409e+23), -2.653433028854124e-14, 8.548717289613705e-15, 1.4988010832439613e-15, -1.942890293094024e-15, -1.0813966570844462, 5.700995231450179e-14, -2.5895952049381776e-14, 2.3675506000131463e-14, -1.6431300764452317e-14, -0.25157545390137065, -5.387357226993572e-14, 2.7269853042355408e-14, -2.1371793224034263e-14, 1.0436096431476471e-14, 0.010905629305099168, 3.7192471324942744e-14, 0.0, 1.4016565685892601e-14, -2.220446049250313e-15, 0.07340281760410261, -1.6903145549918008e-14, -7.16093850883226e-15, -4.496403249731884e-15, -6.38378239159465e-15, 0.07094523951830371, -8.93729534823251e-15, 3.989863994746656e-15, -4.947431353485854e-15, 8.000544671205034e-15, 0.052045427125944094, 3.0021124475254624e-14, -2.868538739875248e-14, 1.045864783666417e-14, -1.2753686995381486e-14, 0.03209567465551058, -2.702504019180818e-14, 2.2815083156046967e-14, -1.0707580655466842e-14, 9.298117831235686e-15, 0.016645459562018725, 1.582891803741937e-14, -1.8591031492043442e-14, 6.243269790040529e-15, -1.161050422471277e-14, 0.007306044316871138, -4.163336342344337e-16, -5.995204332975845e-15, -3.0270924655795284e-16, -2.5604518505417673e-15, 0.0013483078617338717, -1.4431598277520052e-14, 8.81239525796218e-15, -5.2497069191748125e-15, 5.689893001203927e-15, -0.00029612196884580555, 3.056756237018732e-14, -2.998989945268704e-14, 1.1934030152982444e-14, -7.261552470438914e-15, -0.001678915953534782, -3.294651877705501e-14, 4.359013150434521e-14, -1.266738450245164e-14, 1.3766765505351941e-14, -0.00048093234813764707, 1.9456875346990365e-14, -2.6353919047039653e-14, 7.25591461914199e-15, -1.074140776324839e-14, -0.0008217947318864237, -6.097553018058477e-15, 3.344546861683284e-15, -2.4485621863412632e-15, -6.661338147750939e-16])

cheby_P1_P3_fit = cheby_P1_P3_fit.reshape((15,5))

cheby_P1_P3_fit


array([[ 1.22764389e+01, -2.65343303e-14,  8.54871729e-15,
         1.49880108e-15, -1.94289029e-15],
       [-1.08139666e+00,  5.70099523e-14, -2.58959520e-14,
         2.36755060e-14, -1.64313008e-14],
       [-2.51575454e-01, -5.38735723e-14,  2.72698530e-14,
        -2.13717932e-14,  1.04360964e-14],
       [ 1.09056293e-02,  3.71924713e-14,  0.00000000e+00,
         1.40165657e-14, -2.22044605e-15],
       [ 7.34028176e-02, -1.69031455e-14, -7.16093851e-15,
        -4.49640325e-15, -6.38378239e-15],
       [ 7.09452395e-02, -8.93729535e-15,  3.98986399e-15,
        -4.94743135e-15,  8.00054467e-15],
       [ 5.20454271e-02,  3.00211245e-14, -2.86853874e-14,
         1.04586478e-14, -1.27536870e-14],
       [ 3.20956747e-02, -2.70250402e-14,  2.28150832e-14,
        -1.07075807e-14,  9.29811783e-15],
       [ 1.66454596e-02,  1.58289180e-14, -1.85910315e-14,
         6.24326979e-15, -1.16105042e-14],
       [ 7.30604432e-03, -4.16333634e-16, -5.99520433e-15,
        -3.02709247e-16

In [18]:
#P1->P6
# CH2 + H2O = H + CH3O
cheby_P1_P6_fit = np.array([-19.695165522471957+np.log10(6.0221409e+23), 2.9753977059954195e-14, -2.3425705819590803e-14, 2.9976021664879227e-14, -5.329070518200751e-15, 6.464644733241395, -4.551914400963142e-15, 4.57897608718838e-14, 5.218048215738236e-15, 4.440892098500626e-16, 0.1954714751628971, 3.7969627442180354e-14, -6.275535646693697e-14, 7.993605777301127e-15, -1.4876988529977098e-14, 0.14263958549650058, -3.5083047578154947e-14, 5.706546346573305e-14, -4.884981308350689e-15, 5.23192600354605e-15, 0.07746889312470806, 6.483702463810914e-14, -4.1744385725905886e-14, 2.55351295663786e-14, -1.532107773982716e-14, 0.038318153793188925, -5.3290705182007514e-14, 8.465450562766819e-14, -1.3850032232198828e-14, 4.068273495860808e-14, 0.01839121282014003, 7.646661082105766e-14, -7.455147610357926e-14, 3.147482274812319e-14, -3.9968028886505635e-14, 0.009020244948997114, -8.248642654334892e-14, 7.527312106958561e-14, -3.215093122288515e-14, 3.1807889655510735e-14, 0.004446765495699612, 5.960336391108711e-14, -6.372680161348399e-14, 2.4912363838502927e-14, -2.8949065367100957e-14, 0.0020485332744472617, -2.1356614393619466e-14, 1.149080830487037e-14, -1.0960850282959456e-14, -2.3314683517128287e-15, 0.001219019676920119, -1.7624356835055366e-14, 1.0047518372857667e-14, -5.171644362755856e-15, 1.6542323066914832e-14, 0.0005822849800587622, 4.7188815355259095e-14, -5.10702591327572e-14, 1.604879423799943e-14, -1.8408885527065877e-14, 0.0003878147018800959, -5.9200257543357e-14, 6.789013795582832e-14, -2.091122414116242e-14, 2.2537527399890678e-14, 9.66462194333384e-05, 4.364087216601753e-14, -3.855249453010856e-14, 1.5493682725686853e-14, -1.3600232051658168e-14, 0.00018824414738862622, -1.9349973012783295e-14, 1.3711254354120683e-14, -7.060758228094599e-15, 1.1102230246251565e-15])

cheby_P1_P6_fit = cheby_P1_P6_fit.reshape((15,5))

cheby_P1_P6_fit

array([[ 4.08458539e+00,  2.97539771e-14, -2.34257058e-14,
         2.99760217e-14, -5.32907052e-15],
       [ 6.46464473e+00, -4.55191440e-15,  4.57897609e-14,
         5.21804822e-15,  4.44089210e-16],
       [ 1.95471475e-01,  3.79696274e-14, -6.27553565e-14,
         7.99360578e-15, -1.48769885e-14],
       [ 1.42639585e-01, -3.50830476e-14,  5.70654635e-14,
        -4.88498131e-15,  5.23192600e-15],
       [ 7.74688931e-02,  6.48370246e-14, -4.17443857e-14,
         2.55351296e-14, -1.53210777e-14],
       [ 3.83181538e-02, -5.32907052e-14,  8.46545056e-14,
        -1.38500322e-14,  4.06827350e-14],
       [ 1.83912128e-02,  7.64666108e-14, -7.45514761e-14,
         3.14748227e-14, -3.99680289e-14],
       [ 9.02024495e-03, -8.24864265e-14,  7.52731211e-14,
        -3.21509312e-14,  3.18078897e-14],
       [ 4.44676550e-03,  5.96033639e-14, -6.37268016e-14,
         2.49123638e-14, -2.89490654e-14],
       [ 2.04853327e-03, -2.13566144e-14,  1.14908083e-14,
        -1.09608503e-14

In [19]:
#P1->P4
# CH2 + H2O = H2CO + H2

cheby_P1_P4_fit = np.array([-12.97823248977664+np.log10(6.0221409e+23), 7.593925488436071e-14, -3.4361402612148595e-14, 5.127842594987442e-14, -1.4432899320127035e-14, -0.8865276325900253, -6.841749389252527e-14, 1.1863426907510188e-13, -3.70536934468646e-14, 4.288236432614667e-14, -0.1297285460188507, 5.974387651264124e-14, -4.696243394164412e-14, 3.0933589023618424e-14, -1.7583157152500917e-14, 0.08490236480963625, -3.988476215965875e-14, 4.75175454539567e-14, -1.812439087700568e-14, 1.452310494087783e-14, 0.1112584954318046, 4.599098879509711e-14, -2.366162821232365e-14, 2.468858451010192e-14, -1.3489209749195652e-14, 0.08678252075544635, -3.980149543281186e-14, 3.95516952522712e-14, -1.7111312367035225e-14, 2.0056005467505855e-14, 0.05469600097000824, 3.712308238590367e-14, -2.907396545737129e-14, 1.3548190347378863e-14, -1.3378187446733136e-14, 0.029144637643761767, -1.9399412631848634e-14, 1.6944778913341452e-14, -8.152332975353005e-15, 7.951972413877684e-15, 0.012632006167920155, 1.8362047993214503e-15, -8.406469964583607e-15, 9.037909309839165e-16, -9.669348655094723e-15, 0.003509632659360093, 1.2167784141370319e-14, -1.0727529975440575e-14, 4.723652025084846e-15, -4.697631172945194e-15, -0.00017030969065366663, -3.623013347664461e-14, 2.1756901835701115e-14, -1.3996182685049874e-14, 9.173217740965356e-15, -0.0014977335203483627, 6.931868273829522e-14, -5.699607452669397e-14, 2.685004996116902e-14, -1.2444906216657614e-14, -0.0010198578943847042, -7.861853529300689e-14, 7.414902025715264e-14, -3.091537442712067e-14, 2.0872192862952943e-14, -0.0005694174803873575, 5.527089202983504e-14, -4.694855615383631e-14, 2.1203525046864513e-14, -1.5785983631388945e-14, 3.743973682859836e-05, -2.9443461557754347e-14, 2.0095036745715333e-14, -1.1546319456101628e-14, 3.3861802251067274e-15])

cheby_P1_P4_fit = cheby_P1_P4_fit.reshape((15,5))

cheby_P1_P4_fit

array([[ 1.08015184e+01,  7.59392549e-14, -3.43614026e-14,
         5.12784259e-14, -1.44328993e-14],
       [-8.86527633e-01, -6.84174939e-14,  1.18634269e-13,
        -3.70536934e-14,  4.28823643e-14],
       [-1.29728546e-01,  5.97438765e-14, -4.69624339e-14,
         3.09335890e-14, -1.75831572e-14],
       [ 8.49023648e-02, -3.98847622e-14,  4.75175455e-14,
        -1.81243909e-14,  1.45231049e-14],
       [ 1.11258495e-01,  4.59909888e-14, -2.36616282e-14,
         2.46885845e-14, -1.34892097e-14],
       [ 8.67825208e-02, -3.98014954e-14,  3.95516953e-14,
        -1.71113124e-14,  2.00560055e-14],
       [ 5.46960010e-02,  3.71230824e-14, -2.90739655e-14,
         1.35481903e-14, -1.33781874e-14],
       [ 2.91446376e-02, -1.93994126e-14,  1.69447789e-14,
        -8.15233298e-15,  7.95197241e-15],
       [ 1.26320062e-02,  1.83620480e-15, -8.40646996e-15,
         9.03790931e-16, -9.66934866e-15],
       [ 3.50963266e-03,  1.21677841e-14, -1.07275300e-14,
         4.72365203e-15

In [20]:
#P1->P5
# CH2 + H2O = H + CH2OH

cheby_P1_P5_fit = np.array([-13.653927469775583+np.log10(6.0221409e+23), 2.4646951146678475e-14, -1.5210055437364645e-14, 1.4432899320127035e-14, -4.551914400963142e-15, 1.7138062528331277, -3.652633751016765e-14, 4.256837937699487e-14, -1.199040866595169e-14, 5.551115123125783e-15, 0.16100528958500612, 5.0931481254679056e-14, -7.673028878940613e-14, 1.8041124150158794e-14, -1.9539925233402755e-14, 0.1252439635067451, -5.134781488891349e-14, 7.91033905045424e-14, -1.7430501486614958e-14, 1.7132129048746947e-14, 0.07108348197901149, 5.35682609381638e-14, -8.709699628184353e-14, 2.2121193765656244e-14, -3.3861802251067274e-14, 0.037074471366544445, -4.043987367197133e-14, 9.192646643896296e-14, -1.742356259271105e-14, 3.766084666345648e-14, 0.01808948018643522, 3.804248582817138e-14, -3.799738301779598e-14, 1.539957397711511e-14, -1.9692580899288714e-14, 0.008419890172966571, -2.3522254023050637e-14, 1.6209256159527285e-14, -9.37336146200618e-15, 8.923417560424696e-15, 0.003774285534072823, -1.56472057533108e-15, 1.4051260155412137e-15, -7.827939685345342e-16, -5.84601811404184e-15, 0.0021259247811710735, 2.7119907881900662e-14, -3.9246383920499284e-14, 1.047209194360299e-14, -1.519617764955683e-14, 0.000658730180708729, -5.298772488490644e-14, 5.3609894301587246e-14, -2.1073203945731755e-14, 2.4424906541753444e-14, 0.0006816662079840961, 6.706744534734632e-14, -7.674416657721395e-14, 2.6805380831662617e-14, -2.5035962886166274e-14, -7.39557727502671e-05, -6.147838314818355e-14, 7.349676423018536e-14, -2.4038280047045113e-14, 2.3647750424515834e-14, 0.00011730551947407297, 4.232692755318235e-14, -4.96269692007445e-14, 1.6848718600859236e-14, -1.9220736113823023e-14, 0.0003036156546144253, -1.943790180897187e-14, 1.8360313269738526e-14, -7.76830856585864e-15, 4.773959005888173e-15])

cheby_P1_P5_fit = cheby_P1_P5_fit.reshape((15,5))

cheby_P1_P5_fit

array([[ 1.01258234e+01,  2.46469511e-14, -1.52100554e-14,
         1.44328993e-14, -4.55191440e-15],
       [ 1.71380625e+00, -3.65263375e-14,  4.25683794e-14,
        -1.19904087e-14,  5.55111512e-15],
       [ 1.61005290e-01,  5.09314813e-14, -7.67302888e-14,
         1.80411242e-14, -1.95399252e-14],
       [ 1.25243964e-01, -5.13478149e-14,  7.91033905e-14,
        -1.74305015e-14,  1.71321290e-14],
       [ 7.10834820e-02,  5.35682609e-14, -8.70969963e-14,
         2.21211938e-14, -3.38618023e-14],
       [ 3.70744714e-02, -4.04398737e-14,  9.19264664e-14,
        -1.74235626e-14,  3.76608467e-14],
       [ 1.80894802e-02,  3.80424858e-14, -3.79973830e-14,
         1.53995740e-14, -1.96925809e-14],
       [ 8.41989017e-03, -2.35222540e-14,  1.62092562e-14,
        -9.37336146e-15,  8.92341756e-15],
       [ 3.77428553e-03, -1.56472058e-15,  1.40512602e-15,
        -7.82793969e-16, -5.84601811e-15],
       [ 2.12592478e-03,  2.71199079e-14, -3.92463839e-14,
         1.04720919e-14

In [22]:
#P4->P6
# H2CO + H2 = H + CH3O

cheby_P4_P6_fit = np.array([-61.32866442669138+np.log10(6.0221409e+23), -2.3092638912203256e-14, 9.237055564881302e-14, 4.1744385725905886e-14, 8.348877145181177e-14, 42.64350314698601, 1.412203687323199e-13, 1.0902390101819037e-13, 6.661338147750939e-14, -4.618527782440651e-14, 0.24998699131869762, -3.9968028886505635e-14, -2.30593322214645e-13, -4.39648317751562e-14, -3.9968028886505635e-14, 0.15289943870607914, -4.618527782440651e-14, 1.8474111129762605e-13, -4.440892098500626e-15, 5.855038676116919e-14, 0.07848439225886494, 1.376676550535194e-13, -2.3447910280083306e-13, 2.353672812205332e-14, -1.234568003383174e-13, 0.03799084285937693, -2.4424906541753444e-13, 3.0242475190789264e-13, -1.219024881038422e-13, 1.6170398353665405e-13, 0.01796135442620206, 2.4213964167074664e-13, -2.2470914018413168e-13, 1.0071804501521342e-13, -1.5987211554602254e-13, 0.008578831832851463, -2.7081635545211924e-13, 1.8207657603852567e-13, -1.0398973349090568e-13, 1.0036416142611415e-13, 0.004058218905757194, 2.0854151738802784e-13, -1.9184653865522705e-13, 8.915090887740007e-14, -9.248157795127554e-14, 0.0017630043456875466, -1.3070100557399655e-13, 6.394884621840902e-14, -6.523948048453576e-14, -6.661338147750939e-15, 0.0010272200103391693, 4.64628335805628e-14, -2.986499936241671e-14, 2.5712071360928235e-14, 5.062616992290714e-14, 0.000468937913462919, 4.5553838479150954e-14, -8.748557434046234e-14, 1.1907141939104804e-14, -5.6066262743570405e-14, 0.0003363454869793614, -1.1944958910881098e-13, 1.936228954946273e-13, -3.390343561449072e-14, 7.904787935331115e-14, 7.581283187274579e-05, 1.3115550312470248e-13, -1.4699352846037073e-13, 4.3510334224450276e-14, -6.17284001691587e-14, 0.00017927464658229475, -9.567346914707286e-14, 9.325873406851315e-14, -4.158479116611602e-14, 2.220446049250313e-14])

cheby_P4_P6_fit = cheby_P4_P6_fit.reshape((15,5))

cheby_P4_P6_fit

array([[-3.75489135e+01, -2.30926389e-14,  9.23705556e-14,
         4.17443857e-14,  8.34887715e-14],
       [ 4.26435031e+01,  1.41220369e-13,  1.09023901e-13,
         6.66133815e-14, -4.61852778e-14],
       [ 2.49986991e-01, -3.99680289e-14, -2.30593322e-13,
        -4.39648318e-14, -3.99680289e-14],
       [ 1.52899439e-01, -4.61852778e-14,  1.84741111e-13,
        -4.44089210e-15,  5.85503868e-14],
       [ 7.84843923e-02,  1.37667655e-13, -2.34479103e-13,
         2.35367281e-14, -1.23456800e-13],
       [ 3.79908429e-02, -2.44249065e-13,  3.02424752e-13,
        -1.21902488e-13,  1.61703984e-13],
       [ 1.79613544e-02,  2.42139642e-13, -2.24709140e-13,
         1.00718045e-13, -1.59872116e-13],
       [ 8.57883183e-03, -2.70816355e-13,  1.82076576e-13,
        -1.03989733e-13,  1.00364161e-13],
       [ 4.05821891e-03,  2.08541517e-13, -1.91846539e-13,
         8.91509089e-14, -9.24815780e-14],
       [ 1.76300435e-03, -1.30701006e-13,  6.39488462e-14,
        -6.52394805e-14

In [23]:
#R->P2
#CH3 + OH = cis-HCOH + H2

cheby_R_P2_fit = np.array([-12.202077899566882+np.log10(6.0221409e+23), 3.7594927171369363e-14, -9.01362318117549e-15, 2.901151541223612e-14, -2.5049406993105094e-15, -0.14060717151046576, -3.298403217222301e-14, 6.127043317150083e-15, -1.3143999777476267e-14, -9.793164543192567e-15, 0.04486404366824373, 3.212572352237486e-14, -3.9440672949808686e-14, 8.864436962241484e-15, -1.2185456636781833e-14, 0.08240495933008374, -2.3016311079260277e-14, 3.846228890935777e-14, -3.672409598642901e-15, 8.066355743074904e-15, 0.05302646512132361, 4.287889487919472e-14, -2.5748500553923748e-14, 1.5461590341381282e-14, -1.7649944006326024e-14, 0.026805621857993196, -3.1009916856561404e-14, 4.8950210204679045e-14, -1.0346758172463666e-14, 2.5856487090303304e-14, 0.012207201401325508, 3.823330541052883e-14, -4.139397158375857e-14, 1.690748235860795e-14, -1.6965595595053173e-14, 0.005266217313211852, -3.9059359045745534e-14, 3.4139358007223564e-14, -1.555678329212551e-14, 1.2954914918594795e-14, 0.002244037720790953, 2.2298569241074873e-14, -2.0979745718463505e-14, 8.783772320608563e-15, -1.1386724896311762e-14, 0.0009453154595230676, -5.139118297581291e-17, -9.413910623257138e-15, -3.178880769727499e-16, -6.8486882831564344e-15, 0.00045759571601953347, -2.3920535691113187e-14, 2.4766647066520875e-14, -8.206759924411777e-15, 1.3281042932078435e-14, 0.00018660670912437442, 4.5076572682822835e-14, -5.0872500656495845e-14, 1.6652044326770366e-14, -1.5485876470044957e-14, 0.0001249050642638319, -5.0204632118244774e-14, 6.227050125540146e-14, -1.854245923471609e-14, 2.1073420786166253e-14, 3.817468821486767e-05, 3.9250070207885734e-14, -4.2656850274269686e-14, 1.4881759019536034e-14, -1.607654981361506e-14, 3.30162648419334e-05, -2.2316566997138132e-14, 2.139607935269794e-14, -8.50795128792825e-15, 4.683536544702882e-15])

cheby_R_P2_fit = cheby_R_P2_fit.reshape((15,5))

cheby_R_P2_fit

array([[ 1.15776730e+01,  3.75949272e-14, -9.01362318e-15,
         2.90115154e-14, -2.50494070e-15],
       [-1.40607172e-01, -3.29840322e-14,  6.12704332e-15,
        -1.31439998e-14, -9.79316454e-15],
       [ 4.48640437e-02,  3.21257235e-14, -3.94406729e-14,
         8.86443696e-15, -1.21854566e-14],
       [ 8.24049593e-02, -2.30163111e-14,  3.84622889e-14,
        -3.67240960e-15,  8.06635574e-15],
       [ 5.30264651e-02,  4.28788949e-14, -2.57485006e-14,
         1.54615903e-14, -1.76499440e-14],
       [ 2.68056219e-02, -3.10099169e-14,  4.89502102e-14,
        -1.03467582e-14,  2.58564871e-14],
       [ 1.22072014e-02,  3.82333054e-14, -4.13939716e-14,
         1.69074824e-14, -1.69655956e-14],
       [ 5.26621731e-03, -3.90593590e-14,  3.41393580e-14,
        -1.55567833e-14,  1.29549149e-14],
       [ 2.24403772e-03,  2.22985692e-14, -2.09797457e-14,
         8.78377232e-15, -1.13867249e-14],
       [ 9.45315460e-04, -5.13911830e-17, -9.41391062e-15,
        -3.17888077e-16

In [24]:
#R->P3
#CH3 + OH =trans-HCOH + H2
cheby_R_P3_fit = np.array([-11.448427480199669+np.log10(6.0221409e+23), 3.9190872769268026e-14, -5.115352585960409e-14, 2.6367796834847468e-14, -1.9290125052862095e-14, -0.5055600501187265, -4.604649994632837e-14, 9.627888764018877e-14, -1.3739009929736312e-14, 2.8449465006019636e-14, -0.10222337185352424, 2.0733414984874798e-14, -6.756400994234468e-14, 5.093148125467906e-15, -2.017830347256222e-14, 0.030490486591855055, -2.6104118866498993e-14, 8.182343691487404e-14, -7.271960811294775e-15, 2.3120394487818885e-14, 0.039741179366475504, 4.6102011097559625e-14, -5.342948306008566e-14, 1.8846035843012032e-14, -2.095545958979983e-14, 0.025945642854542858, -4.736488978807074e-14, 6.81087131138014e-14, -1.7883264313844904e-14, 2.5489159394265215e-14, 0.013840645159775122, 5.3714845071883843e-14, -5.064004771071495e-14, 1.9605844725489874e-14, -1.905420266012925e-14, 0.006539755799674363, -3.97895149988059e-14, 3.833044992518353e-14, -1.5361193220209124e-14, 1.4314938123760612e-14, 0.0027971814452542564, 2.4436615925216287e-14, -2.338927662659529e-14, 9.2148511043888e-15, -1.1818671041829987e-14, 0.001051116445920975, -8.910840815223864e-15, -1.3253287356462806e-15, -3.2636653796158654e-15, -3.2578106878844437e-15, 0.00038705072202893306, -1.154696997740512e-14, 1.7116516537463156e-14, -4.49596956886289e-15, 1.078998002057574e-14, 8.904279162908618e-05, 3.6665115388245795e-14, -4.754530102957233e-14, 1.464345138202372e-14, -1.4786782909226304e-14, 6.29020276417605e-05, -4.133943621448255e-14, 5.6343818499726694e-14, -1.6670909444571613e-14, 1.867950238931826e-14, 9.21374625781346e-06, 2.9179675169188624e-14, -3.8007791358651843e-14, 1.1919285003436642e-14, -1.517536096784511e-14, 2.1388468905713526e-05, -1.7547595321243392e-14, 1.9963197761541096e-14, -7.208643404421622e-15, 4.8155923693116165e-15])

cheby_R_P3_fit = cheby_R_P3_fit.reshape((15,5))

cheby_R_P3_fit

array([[ 1.23313234e+01,  3.91908728e-14, -5.11535259e-14,
         2.63677968e-14, -1.92901251e-14],
       [-5.05560050e-01, -4.60464999e-14,  9.62788876e-14,
        -1.37390099e-14,  2.84494650e-14],
       [-1.02223372e-01,  2.07334150e-14, -6.75640099e-14,
         5.09314813e-15, -2.01783035e-14],
       [ 3.04904866e-02, -2.61041189e-14,  8.18234369e-14,
        -7.27196081e-15,  2.31203945e-14],
       [ 3.97411794e-02,  4.61020111e-14, -5.34294831e-14,
         1.88460358e-14, -2.09554596e-14],
       [ 2.59456429e-02, -4.73648898e-14,  6.81087131e-14,
        -1.78832643e-14,  2.54891594e-14],
       [ 1.38406452e-02,  5.37148451e-14, -5.06400477e-14,
         1.96058447e-14, -1.90542027e-14],
       [ 6.53975580e-03, -3.97895150e-14,  3.83304499e-14,
        -1.53611932e-14,  1.43149381e-14],
       [ 2.79718145e-03,  2.44366159e-14, -2.33892766e-14,
         9.21485110e-15, -1.18186710e-14],
       [ 1.05111645e-03, -8.91084082e-15, -1.32532874e-15,
        -3.26366538e-15

In [25]:
#R->P1
# CH3 + OH =CH2 + H2O
cheby_R_P1_fit = np.array([-10.866982254042247+np.log10(6.0221409e+23), -8.923417560424696e-15, 1.0227929614359255e-14, 6.342149028171207e-15, 3.219646771412954e-15, -0.2989122499569471, 1.835337437583462e-14, 2.5946259030185104e-14, 6.25888230132432e-15, 1.1407541578023483e-14, -0.20800433901477805, -4.773959005888173e-15, -9.766493169749424e-15, -1.2906342661267445e-15, -1.186550857568136e-15, -0.03295053899276898, -1.9567680809018384e-15, 1.501229696110329e-14, -1.1102230246251565e-16, -9.228728892196614e-16, 0.01044241823318634, 1.8457457784393227e-14, -1.0179357357031904e-14, 8.385653282871885e-15, -7.993605777301127e-15, 0.015595574900668832, -1.837419105754634e-14, 1.5839760059144226e-14, -8.35095881335235e-15, 1.099120794378905e-14, 0.011542817542581858, 2.995867443011946e-14, -3.077746391078051e-14, 1.1119740111337206e-14, -1.4155343563970746e-14, 0.0068851315253593975, -2.796036785348427e-14, 2.7006175074006933e-14, -1.0737816343552031e-14, 1.0630385460785874e-14, 0.003620956346562886, 2.282755148103055e-14, -2.6098914696071063e-14, 8.731839036546507e-15, -1.3219460248681258e-14, 0.0016705449652879775, -1.2775479459048444e-14, 3.639449852599341e-15, -4.847142652530945e-15, -1.2455314557513475e-15, 0.0007320530771785221, -1.2022582365420198e-15, 4.562322741819003e-15, -5.912425497106577e-16, 7.438494264988549e-15, 0.00024159894549302674, 1.9213390644104433e-14, -2.679106936298581e-14, 7.685909200749741e-15, -9.17668718791731e-15, 9.736556882067315e-05, -3.0050628326873385e-14, 3.823677485748078e-14, -1.233670283984356e-14, 1.2365108936762681e-14, 3.3963993417159e-05, 2.2195664902378842e-14, -2.404153265356257e-14, 9.258896817646023e-15, -9.867107131356079e-15, 3.487934995245745e-05, -1.009194355687526e-14, 5.266620473065586e-15, -4.550992829116529e-15, 6.938893903907228e-17])

cheby_R_P1_fit = cheby_R_P1_fit.reshape((15,5))

cheby_R_P1_fit

array([[ 1.29127687e+01, -8.92341756e-15,  1.02279296e-14,
         6.34214903e-15,  3.21964677e-15],
       [-2.98912250e-01,  1.83533744e-14,  2.59462590e-14,
         6.25888230e-15,  1.14075416e-14],
       [-2.08004339e-01, -4.77395901e-15, -9.76649317e-15,
        -1.29063427e-15, -1.18655086e-15],
       [-3.29505390e-02, -1.95676808e-15,  1.50122970e-14,
        -1.11022302e-16, -9.22872889e-16],
       [ 1.04424182e-02,  1.84574578e-14, -1.01793574e-14,
         8.38565328e-15, -7.99360578e-15],
       [ 1.55955749e-02, -1.83741911e-14,  1.58397601e-14,
        -8.35095881e-15,  1.09912079e-14],
       [ 1.15428175e-02,  2.99586744e-14, -3.07774639e-14,
         1.11197401e-14, -1.41553436e-14],
       [ 6.88513153e-03, -2.79603679e-14,  2.70061751e-14,
        -1.07378163e-14,  1.06303855e-14],
       [ 3.62095635e-03,  2.28275515e-14, -2.60989147e-14,
         8.73183904e-15, -1.32194602e-14],
       [ 1.67054497e-03, -1.27754795e-14,  3.63944985e-15,
        -4.84714265e-15

In [26]:
#R->P6
# CH3 + OH = H + CH3O

cheby_R_P6_fit = np.array([-19.039384705434003+np.log10(6.0221409e+23), -2.3092638912203256e-14, 1.787459069646502e-14, -2.220446049250313e-16, 1.3322676295501878e-14, 6.658194275483846, 4.063416270128073e-14, 4.9987791683747673e-14, 1.7208456881689926e-14, 9.547918011776346e-15, 0.08222350846655802, 1.8096635301390052e-14, -3.089195566019498e-14, 1.0436096431476471e-14, -1.4654943925052066e-14, 0.07005243262561622, -3.419486915845482e-14, 6.972200594645983e-14, -1.84297022087776e-14, 2.1923435289394888e-14, 0.034337685233370774, 7.049916206369744e-14, -4.218847493575595e-14, 3.019806626980426e-14, -2.375877272697835e-14, 0.013262111381945219, -5.306866057708248e-14, 7.893685705084863e-14, -2.32314167902814e-14, 4.220235272356376e-14, 0.004248522103378977, 5.6565863104651726e-14, -6.117328865684613e-14, 2.2249563302878528e-14, -3.8968828164342995e-14, 0.001236144971541231, -5.253783519343358e-14, 5.140332604014475e-14, -1.9057672107081203e-14, 2.5979218776228663e-14, 0.00026687454002385924, 4.1537953632264646e-14, -5.1181281435219717e-14, 1.5432100042289676e-14, -2.556288514199423e-14, -6.499026255951668e-05, -2.7427712878669297e-14, 2.220446049250313e-14, -1.1393663790215669e-14, -6.106226635438361e-16, 6.341331312698095e-05, 2.9199732909379605e-15, -1.0560996521746802e-14, -1.734723475976807e-18, 1.2323475573339238e-14, 7.598107454320421e-05, 1.7241416627733486e-14, -2.3037127760971998e-14, 7.79064313061184e-15, -1.1587952819525071e-14, 3.958844643459081e-05, -2.8406096919120216e-14, 4.579669976578771e-14, -1.1128251098391218e-14, 1.9761969838327786e-14, 6.146547880669928e-06, 1.7400143825785364e-14, -2.1149748619109232e-14, 7.473188734508085e-15, -1.2323475573339238e-14, 6.497769317470592e-05, -9.130717015803924e-15, 5.551115123125783e-16, -4.647324192141866e-15, -2.9976021664879227e-15])

cheby_R_P6_fit = cheby_R_P6_fit.reshape((15,5))

cheby_R_P6_fit

array([[ 4.74036621e+00, -2.30926389e-14,  1.78745907e-14,
        -2.22044605e-16,  1.33226763e-14],
       [ 6.65819428e+00,  4.06341627e-14,  4.99877917e-14,
         1.72084569e-14,  9.54791801e-15],
       [ 8.22235085e-02,  1.80966353e-14, -3.08919557e-14,
         1.04360964e-14, -1.46549439e-14],
       [ 7.00524326e-02, -3.41948692e-14,  6.97220059e-14,
        -1.84297022e-14,  2.19234353e-14],
       [ 3.43376852e-02,  7.04991621e-14, -4.21884749e-14,
         3.01980663e-14, -2.37587727e-14],
       [ 1.32621114e-02, -5.30686606e-14,  7.89368571e-14,
        -2.32314168e-14,  4.22023527e-14],
       [ 4.24852210e-03,  5.65658631e-14, -6.11732887e-14,
         2.22495633e-14, -3.89688282e-14],
       [ 1.23614497e-03, -5.25378352e-14,  5.14033260e-14,
        -1.90576721e-14,  2.59792188e-14],
       [ 2.66874540e-04,  4.15379536e-14, -5.11812814e-14,
         1.54321000e-14, -2.55628851e-14],
       [-6.49902626e-05, -2.74277129e-14,  2.22044605e-14,
        -1.13936638e-14

In [27]:
#P4->P5
# H2CO + H2 =  H + CH2OH

cheby_P4_P5_fit = np.array([-55.51212607262686+np.log10(6.0221409e+23), -8.348877145181177e-14, -2.4868995751603507e-14, 7.993605777301127e-15, 1.9539925233402755e-14, 38.00052014440393, 1.687538997430238e-13, 1.6583956430338276e-13, 5.995204332975845e-14, 4.440892098500626e-14, 0.2629769376197051, -3.197442310920451e-14, 9.597878047884478e-14, 6.661338147750939e-15, 6.483702463810914e-14, 0.15320655367066216, 5.329070518200751e-15, -4.263256414560601e-14, 7.105427357601002e-15, -1.4099832412739488e-14, 0.07716033554911483, 9.281464485866309e-14, -4.4853010194856324e-14, 4.707345624410664e-14, -8.171241461241152e-14, 0.037168103179907375, -7.72715225139109e-14, 1.3722356584366935e-13, -2.8310687127941492e-14, 1.224020884649235e-13, 0.016998734335943233, 1.1862733018119798e-13, -9.481304630298837e-14, 5.863365348801608e-14, -1.2034817586936697e-13, 0.007379935798143666, -1.7176364497384355e-13, 1.4654943925052066e-13, -6.455946888195285e-14, 9.547918011776346e-14, 0.003000080220841639, 1.5028256417082275e-13, -1.844080443902385e-13, 5.759281940243e-14, -8.415490526658687e-14, 0.0015753666912827757, -1.0071804501521342e-13, 1.0391687510491465e-13, -4.583833312921115e-14, 5.329070518200751e-15, 0.000349711019064447, 3.779268564763072e-14, -1.0180745135812685e-13, 1.3010426069826053e-14, 2.398081733190338e-14, 0.0005086403279492835, 3.6234903966203547e-14, 8.659739592076221e-15, 1.9172163856495672e-14, -1.837419105754634e-14, -0.0001019173403626894, -9.992874583364397e-14, 8.881784197001252e-14, -4.000272335602517e-14, 4.3076653355456074e-14, 0.00010902927289224706, 1.0525608162836875e-13, -9.237055564881302e-14, 4.387809560135736e-14, -4.04121180963557e-14, 0.00024501237998514336, -7.038813976123492e-14, 4.1522341120980855e-14, -3.410466353770403e-14, 4.440892098500626e-15])

cheby_P4_P5_fit = cheby_P4_P5_fit.reshape((15,5))

cheby_P4_P5_fit

array([[-3.17323752e+01, -8.34887715e-14, -2.48689958e-14,
         7.99360578e-15,  1.95399252e-14],
       [ 3.80005201e+01,  1.68753900e-13,  1.65839564e-13,
         5.99520433e-14,  4.44089210e-14],
       [ 2.62976938e-01, -3.19744231e-14,  9.59787805e-14,
         6.66133815e-15,  6.48370246e-14],
       [ 1.53206554e-01,  5.32907052e-15, -4.26325641e-14,
         7.10542736e-15, -1.40998324e-14],
       [ 7.71603355e-02,  9.28146449e-14, -4.48530102e-14,
         4.70734562e-14, -8.17124146e-14],
       [ 3.71681032e-02, -7.72715225e-14,  1.37223566e-13,
        -2.83106871e-14,  1.22402088e-13],
       [ 1.69987343e-02,  1.18627330e-13, -9.48130463e-14,
         5.86336535e-14, -1.20348176e-13],
       [ 7.37993580e-03, -1.71763645e-13,  1.46549439e-13,
        -6.45594689e-14,  9.54791801e-14],
       [ 3.00008022e-03,  1.50282564e-13, -1.84408044e-13,
         5.75928194e-14, -8.41549053e-14],
       [ 1.57536669e-03, -1.00718045e-13,  1.03916875e-13,
        -4.58383331e-14

In [28]:
#R->P4
# CH3 + OH =H2CO + H2

cheby_R_P4_fit = np.array([-12.910646542678267+np.log10(6.0221409e+23), 1.5182299861749016e-14, 3.226585665316861e-16, 2.4480417692984702e-14, -2.5673907444456745e-15, -0.28866340434880505, -2.375877272697835e-14, 1.2050907147176382e-14, -1.5751289161869408e-14, 3.712308238590367e-15, 0.008527128242729845, -9.8879238130678e-16, 1.675048988403205e-14, 4.85722573273506e-17, 7.639722188201858e-15, 0.08145727954418712, -6.661338147750939e-15, 2.8033131371785203e-14, -1.6306400674181987e-15, 6.054184931159057e-15, 0.059814164199357284, 3.2411573425150664e-14, -3.879882526369727e-14, 1.829786322460336e-14, -2.130240428499519e-14, 0.03233297684936581, -4.6282422339061213e-14, 5.5757481964846534e-14, -2.2390943266170638e-14, 2.4228015427230076e-14, 0.01505893465288326, 6.206190075741524e-14, -6.580846978465615e-14, 2.4666466785783214e-14, -2.5271451598030126e-14, 0.006302899624922843, -5.708020861527885e-14, 5.743322484264013e-14, -2.231591647583464e-14, 1.9907686610309838e-14, 0.0024329562197662035, 4.4486549860556224e-14, -4.8627768478581856e-14, 1.718503811476424e-14, -2.0396878630535298e-14, 0.0008386733113657611, -2.8376823460463108e-14, 2.134056820146668e-14, -1.1334249511163463e-14, 3.7990444123892075e-15, 0.0003801780704913299, 6.763469992399074e-15, -9.880984919163893e-15, 3.271688475692258e-15, 3.594347042223944e-15, 0.00011691176578958878, 2.154700029510792e-14, -2.4001634013615103e-14, 8.339249429889506e-15, -7.912941135668206e-15, 0.00015706858454640066, -3.494904018963574e-14, 3.963496197911809e-14, -1.344670902403422e-14, 1.2538581284360362e-14, 3.814000395476608e-05, 2.942589748256008e-14, -2.7946395197986362e-14, 1.1760991486253758e-14, -1.1450909664922904e-14, 7.56000065013536e-05, -1.337493484021568e-14, 1.2233269952588444e-14, -5.309554879096012e-15, 3.2335245592207684e-15])

cheby_R_P4_fit = cheby_R_P4_fit.reshape((15,5))

cheby_R_P4_fit

array([[ 1.08691044e+01,  1.51822999e-14,  3.22658567e-16,
         2.44804177e-14, -2.56739074e-15],
       [-2.88663404e-01, -2.37587727e-14,  1.20509071e-14,
        -1.57512892e-14,  3.71230824e-15],
       [ 8.52712824e-03, -9.88792381e-16,  1.67504899e-14,
         4.85722573e-17,  7.63972219e-15],
       [ 8.14572795e-02, -6.66133815e-15,  2.80331314e-14,
        -1.63064007e-15,  6.05418493e-15],
       [ 5.98141642e-02,  3.24115734e-14, -3.87988253e-14,
         1.82978632e-14, -2.13024043e-14],
       [ 3.23329768e-02, -4.62824223e-14,  5.57574820e-14,
        -2.23909433e-14,  2.42280154e-14],
       [ 1.50589347e-02,  6.20619008e-14, -6.58084698e-14,
         2.46664668e-14, -2.52714516e-14],
       [ 6.30289962e-03, -5.70802086e-14,  5.74332248e-14,
        -2.23159165e-14,  1.99076866e-14],
       [ 2.43295622e-03,  4.44865499e-14, -4.86277685e-14,
         1.71850381e-14, -2.03968786e-14],
       [ 8.38673311e-04, -2.83768235e-14,  2.13405682e-14,
        -1.13342495e-14

In [29]:
#R->P5
# CH3 + OH =H + CH2OH
cheby_R_P5_fit = np.array([-13.203824999392076+np.log10(6.0221409e+23), 1.2212453270876722e-15, 3.885780586188048e-16, 1.4988010832439613e-14, 1.7763568394002505e-15, 2.124151250608916, 1.6542323066914832e-14, 2.821354261328679e-14, 8.548717289613705e-15, 1.1879386363489175e-14, 0.10772775019181338, -5.467848396278896e-15, -1.4363510381087963e-14, -5.773159728050814e-15, -9.270362255620057e-15, 0.058981229042171957, 1.1157741397482823e-14, 3.2307490016592055e-14, 1.2601031329495527e-14, 1.2542050731312315e-14, 0.02186670040456229, 1.1213252548714081e-14, -1.2601031329495527e-14, -1.8318679906315083e-15, -1.3156142841808105e-14, 0.0060941767361210875, -6.38378239159465e-15, 5.0154325137441447e-14, 1.2073675392798577e-15, 2.5628804634081348e-14, 0.0007078496712989851, 4.2538889077903264e-14, -4.5047299224165727e-14, 1.693220216814062e-14, -2.353672812205332e-14, -0.0006152039632899564, -4.9300190665957366e-14, 4.729550084903167e-14, -1.9404128911298946e-14, 1.9317880628477724e-14, -0.0007281908306402268, 4.143517126631302e-14, -4.5956294325577574e-14, 1.6938707381175533e-14, -2.0174834025610267e-14, -9.917081029028885e-05, -2.7374912232869253e-14, 2.2787327580431338e-14, -1.1561064605647431e-14, 2.7478019859472624e-15, -0.000430046277085705, 5.809805761480824e-15, -8.229528170033973e-15, 2.9085891681268627e-15, 6.716849298982197e-15, 0.00016192515760355027, 1.8004261276294287e-14, -2.3925306180672123e-14, 6.9133067326365705e-15, -9.25821919128822e-15, -0.0002999968957003163, -2.868826053450957e-14, 4.1772141301521515e-14, -1.0622253944492233e-14, 1.532107773982716e-14, 5.3500000499903666e-05, 2.3564700538103445e-14, -2.8144153674247718e-14, 9.001913797712646e-15, -1.2406742300186124e-14, 9.895561595314739e-05, -1.3769367590565906e-14, 1.1504686092678185e-14, -5.6196367004268666e-15, 1.7763568394002505e-15])

cheby_R_P5_fit = cheby_R_P5_fit.reshape((15,5))

cheby_R_P5_fit

array([[ 1.05759259e+01,  1.22124533e-15,  3.88578059e-16,
         1.49880108e-14,  1.77635684e-15],
       [ 2.12415125e+00,  1.65423231e-14,  2.82135426e-14,
         8.54871729e-15,  1.18793864e-14],
       [ 1.07727750e-01, -5.46784840e-15, -1.43635104e-14,
        -5.77315973e-15, -9.27036226e-15],
       [ 5.89812290e-02,  1.11577414e-14,  3.23074900e-14,
         1.26010313e-14,  1.25420507e-14],
       [ 2.18667004e-02,  1.12132525e-14, -1.26010313e-14,
        -1.83186799e-15, -1.31561428e-14],
       [ 6.09417674e-03, -6.38378239e-15,  5.01543251e-14,
         1.20736754e-15,  2.56288046e-14],
       [ 7.07849671e-04,  4.25388891e-14, -4.50472992e-14,
         1.69322022e-14, -2.35367281e-14],
       [-6.15203963e-04, -4.93001907e-14,  4.72955008e-14,
        -1.94041289e-14,  1.93178806e-14],
       [-7.28190831e-04,  4.14351713e-14, -4.59562943e-14,
         1.69387074e-14, -2.01748340e-14],
       [-9.91708103e-05, -2.73749122e-14,  2.27873276e-14,
        -1.15610646e-14

In [30]:
#P2->P3
# cis-HCOH + H2 = trans-HCOH + H2
cheby_P2_P3_fit = np.array([-19.237233579605792+np.log10(6.0221409e+23), -1.4654943925052066e-14, -3.47499806707674e-14, 1.7430501486614958e-14, -1.3322676295501878e-14, 5.358748671939009, 6.994405055138486e-15, -1.0828577617916224e-14, -1.1046719095020308e-14, -1.9761969838327786e-14, -0.05016093342735267, -2.2315482794965646e-14, -5.079270337660091e-14, -2.4980018054066022e-15, -2.2426505097428162e-14, 0.09821276957011982, -2.886579864025407e-15, 4.929390229335695e-14, 2.55351295663786e-15, 2.0847906734289268e-14, 0.1403643880680323, 4.490852134608758e-14, -7.605027718682322e-14, 2.3869795029440866e-14, -4.618527782440651e-14, 0.104313504362473, -6.605826996519681e-14, 9.919842725025774e-14, -2.3925306180672123e-14, 5.3838877800416185e-14, 0.05699651478356628, 8.537615059367454e-14, -8.83182416089312e-14, 3.5334582482171584e-14, -4.3798298321462426e-14, 0.02305214869494232, -7.861549952692393e-14, 7.671641100159832e-14, -3.045816637098353e-14, 3.2307490016592055e-14, 0.004828161734562797, 5.6261419134617796e-14, -6.650235917504688e-14, 2.3208865385093702e-14, -3.1183389204159084e-14, -0.003435995806072789, -3.171117882172503e-14, 2.4202861936828413e-14, -1.423730924821065e-14, 2.220446049250313e-16, -0.0030628377911038895, -6.27980740325329e-15, 1.1379786002407855e-15, -1.6727071117106362e-15, 1.3211653993039363e-14, -0.003164881655833226, 4.5748994870198345e-14, -4.701794509287538e-14, 1.686107850562557e-14, -1.7555401576885288e-14, 0.00015340056964424642, -6.257993255542882e-14, 7.821521208484228e-14, -2.362715058323861e-14, 2.8199664825478976e-14, -0.0005194154975424192, 4.8959317502927924e-14, -4.835021272242557e-14, 1.956876501119087e-14, -1.9317880628477724e-14, 0.0012613859520034763, -1.764040302720815e-14, 1.4765966227514582e-14, -7.464515117128201e-15, 1.887379141862766e-15])

cheby_P2_P3_fit = cheby_P2_P3_fit.reshape((15,5))

cheby_P2_P3_fit


array([[ 4.54251733e+00, -1.46549439e-14, -3.47499807e-14,
         1.74305015e-14, -1.33226763e-14],
       [ 5.35874867e+00,  6.99440506e-15, -1.08285776e-14,
        -1.10467191e-14, -1.97619698e-14],
       [-5.01609334e-02, -2.23154828e-14, -5.07927034e-14,
        -2.49800181e-15, -2.24265051e-14],
       [ 9.82127696e-02, -2.88657986e-15,  4.92939023e-14,
         2.55351296e-15,  2.08479067e-14],
       [ 1.40364388e-01,  4.49085213e-14, -7.60502772e-14,
         2.38697950e-14, -4.61852778e-14],
       [ 1.04313504e-01, -6.60582700e-14,  9.91984273e-14,
        -2.39253062e-14,  5.38388778e-14],
       [ 5.69965148e-02,  8.53761506e-14, -8.83182416e-14,
         3.53345825e-14, -4.37982983e-14],
       [ 2.30521487e-02, -7.86154995e-14,  7.67164110e-14,
        -3.04581664e-14,  3.23074900e-14],
       [ 4.82816173e-03,  5.62614191e-14, -6.65023592e-14,
         2.32088654e-14, -3.11833892e-14],
       [-3.43599581e-03, -3.17111788e-14,  2.42028619e-14,
        -1.42373092e-14

In [31]:
#P2->P5
# cis-HCOH + H2 =H + CH2OH

cheby_P2_P5_fit = np.array([-21.97999056206319+np.log10(6.0221409e+23), -2.353672812205332e-14, 1.1546319456101628e-14, 1.4210854715202004e-14, 8.881784197001252e-15, 9.03766940942961, 8.681944052568724e-14, 3.78239106701983e-14, 4.0745185003743245e-14, 3.552713678800501e-15, 0.23912039053133805, -1.765254609153999e-14, 3.0558888752807434e-14, 2.886579864025407e-15, 1.7541523789077473e-14, 0.1393723967638445, 6.661338147750939e-15, -2.3092638912203256e-14, -1.7763568394002505e-15, -1.4502288259166107e-14, 0.07155021011883544, 2.930988785010413e-14, -1.787459069646502e-14, 1.9539925233402755e-14, -1.7763568394002505e-14, 0.035306119764044186, -3.7969627442180354e-14, 5.562217353372034e-14, -2.3148150063434514e-14, 3.534672554650342e-14, 0.016466824253467044, 6.117328865684613e-14, -5.573319583618286e-14, 2.7120666823421402e-14, -4.1522341120980855e-14, 0.0072034111332648365, -6.74803095346288e-14, 4.8183679268731794e-14, -2.5668703274028815e-14, 2.5646151868841116e-14, 0.002875331090571087, 4.78540818082962e-14, -5.1708637371916666e-14, 1.898828316804213e-14, -2.4674706722294104e-14, 0.001449297107094183, -1.6061804664069257e-14, -5.551115123125783e-16, -7.518291544883482e-15, -9.880984919163893e-15, 0.0002397279321135759, -1.4520936536532858e-14, 1.6930901125533637e-14, -5.308687517358024e-15, 2.275957200481571e-14, 0.0004330226742416954, 4.415565135751365e-14, -5.795364188543317e-14, 1.8237147902944173e-14, -2.5424107263916085e-14, -0.00014590285990312424, -6.058825316457295e-14, 8.404388296412435e-14, -2.3240090407661285e-14, 3.3306690738754696e-14, 9.434145986375597e-05, 5.170820369104767e-14, -6.339373470609644e-14, 2.05313196999235e-14, -2.6645352591003757e-14, 0.00020346405156504432, -2.6212539083747544e-14, 2.758904216193514e-14, -1.1199374760906267e-14, 7.993605777301127e-15])

cheby_P2_P5_fit = cheby_P2_P5_fit.reshape((15,5))

cheby_P2_P5_fit

array([[ 1.79976035e+00, -2.35367281e-14,  1.15463195e-14,
         1.42108547e-14,  8.88178420e-15],
       [ 9.03766941e+00,  8.68194405e-14,  3.78239107e-14,
         4.07451850e-14,  3.55271368e-15],
       [ 2.39120391e-01, -1.76525461e-14,  3.05588888e-14,
         2.88657986e-15,  1.75415238e-14],
       [ 1.39372397e-01,  6.66133815e-15, -2.30926389e-14,
        -1.77635684e-15, -1.45022883e-14],
       [ 7.15502101e-02,  2.93098879e-14, -1.78745907e-14,
         1.95399252e-14, -1.77635684e-14],
       [ 3.53061198e-02, -3.79696274e-14,  5.56221735e-14,
        -2.31481501e-14,  3.53467255e-14],
       [ 1.64668243e-02,  6.11732887e-14, -5.57331958e-14,
         2.71206668e-14, -4.15223411e-14],
       [ 7.20341113e-03, -6.74803095e-14,  4.81836793e-14,
        -2.56687033e-14,  2.56461519e-14],
       [ 2.87533109e-03,  4.78540818e-14, -5.17086374e-14,
         1.89882832e-14, -2.46747067e-14],
       [ 1.44929711e-03, -1.60618047e-14, -5.55111512e-16,
        -7.51829154e-15

In [32]:
#P2->P4
# cis-HCOH + H2 =H2CO + H2

cheby_P2_P4_fit = np.array([-20.760542959653186+np.log10(6.0221409e+23), -4.884981308350689e-15, 6.439293542825908e-15, 1.3100631690576847e-14, 7.327471962526033e-15, 5.617314454801694, 1.021405182655144e-14, -1.6446913275736108e-14, 3.6637359812630166e-15, -2.4868995751603507e-14, 0.09851687858632813, 9.103828801926284e-15, -2.0261570199409107e-14, 2.7755575615628914e-15, 4.551914400963142e-15, 0.17757758088055708, -1.9539925233402755e-14, 6.084022174945858e-14, -9.658940314238862e-15, 1.3222062333895224e-14, 0.1717773351508638, 4.551914400963142e-15, -4.629630012686903e-14, 7.66053886991358e-15, -2.1538326677728037e-14, 0.106420613219875, -4.1744385725905886e-14, 1.0075273948473296e-13, -2.3842039453825237e-14, 5.0487392044828994e-14, 0.048568476526451784, 6.084022174945858e-14, -5.206945985491984e-14, 2.3480132768649575e-14, -3.169686735304822e-14, 0.014297591188672631, -6.106887998763577e-14, 5.540012892879531e-14, -2.3775794701086372e-14, 2.6645352591003757e-14, -0.0001738094839971449, 3.655496044752127e-14, -4.234113060164191e-14, 1.4677495330239765e-14, -2.346040028911034e-14, -0.004134091593315681, -1.2803560295315819e-14, 1.1657341758564144e-15, -7.034954216389444e-15, -4.6629367034256575e-15, -0.0019202118951258673, -1.8507276874218936e-14, 5.800915303666443e-15, -6.294986233668087e-15, 1.2656542480726785e-14, -0.0009038729323776716, 4.753922949740641e-14, -4.063416270128073e-14, 1.7822115311316722e-14, -1.3211653993039363e-14, 0.0013217897055714523, -5.67922445182667e-14, 6.17284001691587e-14, -2.171320848814995e-14, 2.042810365310288e-14, 0.00047805088244035066, 3.7793878270020453e-14, -3.4611202792689255e-14, 1.4697010969344504e-14, -1.459943277382081e-14, 0.0011175002336858593, -2.22778609795804e-14, 1.3822276656583199e-14, -1.0336787747641536e-14, 3.3306690738754696e-15])

cheby_P2_P4_fit = cheby_P2_P4_fit.reshape((15,5))

cheby_P2_P4_fit

array([[ 3.01920795e+00, -4.88498131e-15,  6.43929354e-15,
         1.31006317e-14,  7.32747196e-15],
       [ 5.61731445e+00,  1.02140518e-14, -1.64469133e-14,
         3.66373598e-15, -2.48689958e-14],
       [ 9.85168786e-02,  9.10382880e-15, -2.02615702e-14,
         2.77555756e-15,  4.55191440e-15],
       [ 1.77577581e-01, -1.95399252e-14,  6.08402217e-14,
        -9.65894031e-15,  1.32220623e-14],
       [ 1.71777335e-01,  4.55191440e-15, -4.62963001e-14,
         7.66053887e-15, -2.15383267e-14],
       [ 1.06420613e-01, -4.17443857e-14,  1.00752739e-13,
        -2.38420395e-14,  5.04873920e-14],
       [ 4.85684765e-02,  6.08402217e-14, -5.20694599e-14,
         2.34801328e-14, -3.16968674e-14],
       [ 1.42975912e-02, -6.10688800e-14,  5.54001289e-14,
        -2.37757947e-14,  2.66453526e-14],
       [-1.73809484e-04,  3.65549604e-14, -4.23411306e-14,
         1.46774953e-14, -2.34604003e-14],
       [-4.13409159e-03, -1.28035603e-14,  1.16573418e-15,
        -7.03495422e-15

In [33]:
#P2->P6
# cis-HCOH + H2 =H + CH3O
cheby_P2_P6_fit = np.array([-27.748663677982268+np.log10(6.0221409e+23), -2.220446049250313e-14, -4.1300296516055823e-14, 1.554312234475219e-14, -6.217248937900877e-15, 13.637412454637253, 2.2648549702353193e-14, 1.3426759704060487e-13, -7.771561172376096e-15, 4.1300296516055823e-14, 0.2151274975182056, 1.6431300764452317e-14, -5.845324224651449e-14, 4.218847493575595e-15, -1.199040866595169e-14, 0.13919271037574665, -4.085620730620576e-14, 1.0436096431476471e-13, -5.773159728050814e-15, 3.7837788458006116e-14, 0.07482012004599703, 7.993605777301127e-14, -3.774758283725532e-14, 1.554312234475219e-14, -2.531308496145357e-14, 0.03733362008078889, -7.749356711883593e-14, 1.1335377081422848e-13, -2.7644553313166398e-14, 6.11455330812305e-14, 0.01774450469239308, 7.946421298754558e-14, -7.116529587847253e-14, 3.504488366168346e-14, -5.340172748447003e-14, 0.008311433067762497, -8.537528323193655e-14, 7.37188088351104e-14, -3.189636055278555e-14, 3.930189507173054e-14, 0.0037885087010186558, 6.184462664204915e-14, -8.026912468039882e-14, 2.335631688055173e-14, -3.8191672047105385e-14, 0.0015556826039300198, -3.56398938139435e-14, 3.397282455352979e-14, -1.6035783811929605e-14, -1.1102230246251565e-15, 0.0008907502018585811, -1.1657341758564144e-14, -5.773159728050814e-15, -4.378442053365461e-15, 1.9984014443252818e-14, 0.0003885583434169518, 5.793455992719743e-14, -6.139533326177116e-14, 2.2920901288081552e-14, -2.628453010800058e-14, 0.0002954147059215373, -7.120476083755101e-14, 1.0147438445073931e-13, -2.423668904460996e-14, 3.9745984281580604e-14, 5.6951370872138085e-05, 5.700995231450179e-14, -5.972999872483342e-14, 2.222701189769083e-14, -2.2870594307278225e-14, 0.0001732887784466619, -2.822395095414265e-14, 3.197442310920451e-14, -1.2840423169180326e-14, 6.8833827526759706e-15])

cheby_P2_P6_fit = cheby_P2_P6_fit.reshape((15,5))

cheby_P2_P6_fit

array([[-3.96891277e+00, -2.22044605e-14, -4.13002965e-14,
         1.55431223e-14, -6.21724894e-15],
       [ 1.36374125e+01,  2.26485497e-14,  1.34267597e-13,
        -7.77156117e-15,  4.13002965e-14],
       [ 2.15127498e-01,  1.64313008e-14, -5.84532422e-14,
         4.21884749e-15, -1.19904087e-14],
       [ 1.39192710e-01, -4.08562073e-14,  1.04360964e-13,
        -5.77315973e-15,  3.78377885e-14],
       [ 7.48201200e-02,  7.99360578e-14, -3.77475828e-14,
         1.55431223e-14, -2.53130850e-14],
       [ 3.73336201e-02, -7.74935671e-14,  1.13353771e-13,
        -2.76445533e-14,  6.11455331e-14],
       [ 1.77445047e-02,  7.94642130e-14, -7.11652959e-14,
         3.50448837e-14, -5.34017275e-14],
       [ 8.31143307e-03, -8.53752832e-14,  7.37188088e-14,
        -3.18963606e-14,  3.93018951e-14],
       [ 3.78850870e-03,  6.18446266e-14, -8.02691247e-14,
         2.33563169e-14, -3.81916720e-14],
       [ 1.55568260e-03, -3.56398938e-14,  3.39728246e-14,
        -1.60357838e-14